/*
 Highmaps JS v9.1.2 (2021-08-18)

 Highmaps as a plugin for Highcharts or Highcharts Stock.

 (c) 2011-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(w){a(w);a.Highcharts=w;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function w(a,l,m,r){a.hasOwnProperty(l)||(a[l]=r.apply(null,m))}a=a?a._modules:{};w(a,"Core/Axis/MapAxis.js",[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,l){var h=l.addEvent,r=l.pick,v=function(){return function(a){this.axis=
a}}();l=function(){function a(){}a.compose=function(k){k.keepProps.push("mapAxis");h(k,"init",function(){this.mapAxis||(this.mapAxis=new v(this))});h(k,"getSeriesExtremes",function(){if(this.mapAxis){var d=[];this.isXAxis&&(this.series.forEach(function(g,c){g.useMapGeometry&&(d[c]=g.xData,g.xData=[])}),this.mapAxis.seriesXData=d)}});h(k,"afterGetSeriesExtremes",function(){if(this.mapAxis){var d=this.mapAxis.seriesXData||[],g;if(this.isXAxis){var c=r(this.dataMin,Number.MAX_VALUE);var f=r(this.dataMax,
-Number.MAX_VALUE);this.series.forEach(function(b,k){b.useMapGeometry&&(c=Math.min(c,r(b.minX,c)),f=Math.max(f,r(b.maxX,f)),b.xData=d[k],g=!0)});g&&(this.dataMin=c,this.dataMax=f);this.mapAxis.seriesXData=void 0}}});h(k,"afterSetAxisTranslation",function(){if(this.mapAxis){var d=this.chart,g=d.plotWidth/d.plotHeight;d=d.xAxis[0];var c;"yAxis"===this.coll&&"undefined"!==typeof d.transA&&this.series.forEach(function(d){d.preserveAspectRatio&&(c=!0)});if(c&&(this.transA=d.transA=Math.min(this.transA,
d.transA),g/=(d.max-d.min)/(this.max-this.min),g=1>g?this:d,d=(g.max-g.min)*g.transA,g.mapAxis.pixelPadding=g.len-d,g.minPixelPadding=g.mapAxis.pixelPadding/2,d=g.mapAxis.fixTo)){d=d[1]-g.toValue(d[0],!0);d*=g.transA;if(Math.abs(d)>g.minPixelPadding||g.min===g.dataMin&&g.max===g.dataMax)d=0;g.minPixelPadding-=d}}});h(k,"render",function(){this.mapAxis&&(this.mapAxis.fixTo=void 0)})};return a}();l.compose(a);return l});w(a,"Mixins/ColorSeries.js",[],function(){return{colorPointMixin:{setVisible:function(a){var h=
this,m=a?"show":"hide";h.visible=h.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(h[a])h[a][m]()});this.series.buildKDTree()}},colorSeriesMixin:{optionalAxis:"colorAxis",translateColors:function(){var a=this,l=this.options.nullColor,m=this.colorAxis,r=this.colorKey;(this.data.length?this.data:this.points).forEach(function(h){var u=h.getNestedProperty(r);(u=h.options.color||(h.isNull||null===h.value?l:m&&"undefined"!==typeof u?m.toColor(u,h):h.color||a.color))&&h.color!==u&&(h.color=
u,"point"===a.options.legendType&&h.legendItem&&a.chart.legend.colorizeItem(h,h.visible))})}}}});w(a,"Core/Axis/Color/ColorAxisComposition.js",[a["Core/Color/Color.js"],a["Mixins/ColorSeries.js"],a["Core/Utilities.js"]],function(a,l,m){var h=a.parse,v=l.colorPointMixin,u=l.colorSeriesMixin,k=m.addEvent,d=m.extend,g=m.merge,c=m.pick,f=m.splat,b;(function(b){function a(){var e=this,b=this.options;this.colorAxis=[];b.colorAxis&&(b.colorAxis=f(b.colorAxis),b.colorAxis.forEach(function(b,c){b.index=c;
new B(e,b)}))}function q(e){var b=this,c=function(c){c=e.allItems.indexOf(c);-1!==c&&(b.destroyItem(e.allItems[c]),e.allItems.splice(c,1))},t=[],p,C;(this.chart.colorAxis||[]).forEach(function(e){(p=e.options)&&p.showInLegend&&(p.dataClasses&&p.visible?t=t.concat(e.getDataClassLegendSymbols()):p.visible&&t.push(e),e.series.forEach(function(e){if(!e.options.showInLegend||p.dataClasses)"point"===e.options.legendType?e.points.forEach(function(e){c(e)}):c(e)}))});for(C=t.length;C--;)e.allItems.unshift(t[C])}
function A(e){e.visible&&e.item.legendColor&&e.item.legendSymbol.attr({fill:e.item.legendColor})}function z(){var e=this.chart.colorAxis;e&&e.forEach(function(e,b,c){e.update({},c)})}function x(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()}function D(){var e=this.axisTypes;e?-1===e.indexOf("colorAxis")&&e.push("colorAxis"):this.axisTypes=["colorAxis"]}function t(e){var b=e.prototype.createAxis;e.prototype.createAxis=function(e,t){if("colorAxis"!==
e)return b.apply(this,arguments);var p=new B(this,g(t.axis,{index:this[e].length,isX:!1}));this.isDirtyLegend=!0;this.axes.forEach(function(e){e.series=[]});this.series.forEach(function(e){e.bindAxes();e.isDirtyData=!0});c(t.redraw,!0)&&this.redraw(t.animation);return p}}function C(){this.elem.attr("fill",h(this.start).tweenTo(h(this.end),this.pos),void 0,!0)}function e(){this.elem.attr("stroke",h(this.start).tweenTo(h(this.end),this.pos),void 0,!0)}var p=[],B;b.compose=function(b,c,y,f,g){B||(B=
b);-1===p.indexOf(c)&&(p.push(c),b=c.prototype,b.collectionsWithUpdate.push("colorAxis"),b.collectionsWithInit.colorAxis=[b.addColorAxis],k(c,"afterGetAxes",a),t(c));-1===p.indexOf(y)&&(p.push(y),c=y.prototype,c.fillSetter=C,c.strokeSetter=e);-1===p.indexOf(f)&&(p.push(f),k(f,"afterGetAllItems",q),k(f,"afterColorizeItem",A),k(f,"afterUpdate",z));-1===p.indexOf(g)&&(p.push(g),d(g.prototype,u),d(g.prototype.pointClass.prototype,v),k(g,"afterTranslate",x),k(g,"bindAxes",D))}})(b||(b={}));return b});
w(a,"Core/Axis/Color/ColorAxisDefaults.js",[a["Core/Color/Palette.js"]],function(a){return{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:a.neutralColor40},labels:{overflow:"justify",rotation:0},minColor:a.highlightColor10,maxColor:a.highlightColor100,tickLength:5,showInLegend:!0}});w(a,"Core/Axis/Color/ColorAxis.js",[a["Core/Axis/Axis.js"],a["Core/Color/Color.js"],a["Core/Axis/Color/ColorAxisComposition.js"],
a["Core/Axis/Color/ColorAxisDefaults.js"],a["Core/Globals.js"],a["Core/Legend/LegendSymbol.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,l,m,r,v,u,k,d){var g=this&&this.__extends||function(){var c=function(b,d){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,b){c.__proto__=b}||function(c,b){for(var e in b)b.hasOwnProperty(e)&&(c[e]=b[e])};return c(b,d)};return function(b,d){function t(){this.constructor=b}c(b,d);b.prototype=null===d?Object.create(d):
(t.prototype=d.prototype,new t)}}(),c=l.parse,f=v.noop,b=k.series,A=d.extend,n=d.isNumber,q=d.merge,h=d.pick;l=function(d){function a(b,c){var a=d.call(this,b,c)||this;a.beforePadding=!1;a.chart=void 0;a.coll="colorAxis";a.dataClasses=void 0;a.legendItem=void 0;a.legendItems=void 0;a.name="";a.options=void 0;a.stops=void 0;a.visible=!0;a.init(b,c);return a}g(a,d);a.compose=function(b,c,d,e){m.compose(a,b,c,d,e)};a.prototype.init=function(b,c){var t=b.options.legend||{},e=c.layout?"vertical"!==c.layout:
"vertical"!==t.layout,p=c.visible;t=q(a.defaultColorAxisOptions,c,{showEmpty:!1,title:null,visible:t.enabled&&!1!==p});this.coll="colorAxis";this.side=c.side||e?2:1;this.reversed=c.reversed||!e;this.opposite=!e;d.prototype.init.call(this,b,t);this.userOptions.visible=p;c.dataClasses&&this.initDataClasses(c);this.initStops();this.horiz=e;this.zoomEnabled=!1};a.prototype.initDataClasses=function(b){var a=this.chart,d=this.options,e=b.dataClasses.length,p,f=0,g=a.options.chart.colorCount;this.dataClasses=
p=[];this.legendItems=[];(b.dataClasses||[]).forEach(function(b,t){b=q(b);p.push(b);if(a.styledMode||!b.color)"category"===d.dataClassColor?(a.styledMode||(t=a.options.colors,g=t.length,b.color=t[f]),b.colorIndex=f,f++,f===g&&(f=0)):b.color=c(d.minColor).tweenTo(c(d.maxColor),2>e?.5:t/(e-1))})};a.prototype.hasData=function(){return!!(this.tickPositions||[]).length};a.prototype.setTickPositions=function(){if(!this.dataClasses)return d.prototype.setTickPositions.call(this)};a.prototype.initStops=function(){this.stops=
this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(b){b.color=c(b[1])})};a.prototype.setOptions=function(b){d.prototype.setOptions.call(this,b);this.options.crosshair=this.options.marker};a.prototype.setAxisSize=function(){var b=this.legendSymbol,c=this.chart,d=c.options.legend||{},e,p;b?(this.left=d=b.attr("x"),this.top=e=b.attr("y"),this.width=p=b.attr("width"),this.height=b=b.attr("height"),this.right=c.chartWidth-d-p,this.bottom=c.chartHeight-
e-b,this.len=this.horiz?p:b,this.pos=this.horiz?d:e):this.len=(this.horiz?d.symbolWidth:d.symbolHeight)||a.defaultLegendLength};a.prototype.normalizedValue=function(b){this.logarithmic&&(b=this.logarithmic.log2lin(b));return 1-(this.max-b)/(this.max-this.min||1)};a.prototype.toColor=function(b,c){var a=this.dataClasses,e=this.stops,d;if(a)for(d=a.length;d--;){var f=a[d];var t=f.from;e=f.to;if(("undefined"===typeof t||b>=t)&&("undefined"===typeof e||b<=e)){var g=f.color;c&&(c.dataClass=d,c.colorIndex=
f.colorIndex);break}}else{b=this.normalizedValue(b);for(d=e.length;d--&&!(b>e[d][0]););t=e[d]||e[d+1];e=e[d+1]||t;b=1-(e[0]-b)/(e[0]-t[0]||1);g=t.color.tweenTo(e.color,b)}return g};a.prototype.getOffset=function(){var b=this.legendGroup,c=this.chart.axisOffset[this.side];b&&(this.axisParent=b,d.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=c)};a.prototype.setLegendColor=function(){var b=this.reversed,c=b?1:0;
b=b?0:1;c=this.horiz?[c,0,b,0]:[0,b,0,c];this.legendColor={linearGradient:{x1:c[0],y1:c[1],x2:c[2],y2:c[3]},stops:this.stops}};a.prototype.drawLegendSymbol=function(b,c){var d=b.padding,e=b.options,p=this.horiz,f=h(e.symbolWidth,p?a.defaultLegendLength:12),g=h(e.symbolHeight,p?12:a.defaultLegendLength),t=h(e.labelPadding,p?16:30);e=h(e.itemDistance,10);this.setLegendColor();c.legendSymbol=this.chart.renderer.rect(0,b.baseline-11,f,g).attr({zIndex:1}).add(c.legendGroup);this.legendItemWidth=f+d+(p?
e:t);this.legendItemHeight=g+d+(p?t:0)};a.prototype.setState=function(b){this.series.forEach(function(c){c.setState(b)})};a.prototype.setVisible=function(){};a.prototype.getSeriesExtremes=function(){var c=this.series,d=c.length,a;this.dataMin=Infinity;for(this.dataMax=-Infinity;d--;){var e=c[d];var f=e.colorKey=h(e.options.colorKey,e.colorKey,e.pointValKey,e.zoneAxis,"y");var g=e.pointArrayMap;var k=e[f+"Min"]&&e[f+"Max"];if(e[f+"Data"])var n=e[f+"Data"];else if(g){n=[];g=g.indexOf(f);var y=e.yData;
if(0<=g&&y)for(a=0;a<y.length;a++)n.push(h(y[a][g],y[a]))}else n=e.yData;k?(e.minColorValue=e[f+"Min"],e.maxColorValue=e[f+"Max"]):(n=b.prototype.getExtremes.call(e,n),e.minColorValue=n.dataMin,e.maxColorValue=n.dataMax);"undefined"!==typeof e.minColorValue&&(this.dataMin=Math.min(this.dataMin,e.minColorValue),this.dataMax=Math.max(this.dataMax,e.maxColorValue));k||b.prototype.applyExtremes.call(e)}};a.prototype.drawCrosshair=function(b,c){var a=c&&c.plotX,e=c&&c.plotY,f=this.pos,g=this.len;if(c){var k=
this.toPixels(c.getNestedProperty(c.series.colorKey));k<f?k=f-2:k>f+g&&(k=f+g+2);c.plotX=k;c.plotY=this.len-k;d.prototype.drawCrosshair.call(this,b,c);c.plotX=a;c.plotY=e;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color}))}};a.prototype.getPlotLinePath=function(b){var c=this.left,a=b.translatedValue,
e=this.top;return n(a)?this.horiz?[["M",a-4,e-6],["L",a+4,e-6],["L",a,e],["Z"]]:[["M",c,a],["L",c-6,a+6],["L",c-6,a-6],["Z"]]:d.prototype.getPlotLinePath.call(this,b)};a.prototype.update=function(b,c){var a=this.chart.legend;this.series.forEach(function(b){b.isDirtyData=!0});(b.dataClasses&&a.allItems||this.dataClasses)&&this.destroyItems();d.prototype.update.call(this,b,c);this.legendItem&&(this.setLegendColor(),a.colorizeItem(this,!0))};a.prototype.destroyItems=function(){var b=this.chart;this.legendItem?
b.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(c){b.legend.destroyItem(c)});b.isDirtyLegend=!0};a.prototype.destroy=function(){this.chart.isDirtyLegend=!0;this.destroyItems();d.prototype.destroy.apply(this,[].slice.call(arguments))};a.prototype.remove=function(b){this.destroyItems();d.prototype.remove.call(this,b)};a.prototype.getDataClassLegendSymbols=function(){var b=this,c=b.chart,a=b.legendItems,e=c.options.legend,d=e.valueDecimals,g=e.valueSuffix||"",k;a.length||
b.dataClasses.forEach(function(e,p){var y=e.from,n=e.to,t=c.numberFormatter,q=!0;k="";"undefined"===typeof y?k="< ":"undefined"===typeof n&&(k="> ");"undefined"!==typeof y&&(k+=t(y,d)+g);"undefined"!==typeof y&&"undefined"!==typeof n&&(k+=" - ");"undefined"!==typeof n&&(k+=t(n,d)+g);a.push(A({chart:c,name:k,options:{},drawLegendSymbol:u.drawRectangle,visible:!0,setState:f,isDataClass:!0,setVisible:function(){q=b.visible=!q;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===p&&
b.setVisible(q)})});c.legend.colorizeItem(this,q)}},e))});return a};a.defaultColorAxisOptions=r;a.defaultLegendLength=200;a.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return a}(a);Array.prototype.push.apply(a.keepProps,l.keepProps);"";return l});w(a,"Mixins/ColorMapSeries.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,l,m){var h=m.defined;m=m.addEvent;var v=a.noop;a=a.seriesTypes;m(l,"afterSetState",function(a){this.moveToTopOnHover&&
this.graphic&&this.graphic.attr({zIndex:a&&"hover"===a.state?1:0})});return{colorMapPointMixin:{dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:v,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:a.column.prototype.pointAttribs,colorAttribs:function(a){var k=
{};!h(a.color)||a.state&&"normal"!==a.state||(k[this.colorProp||"fill"]=a.color);return k}}}});w(a,"Maps/MapNavigationOptionsDefault.js",[a["Core/DefaultOptions.js"],a["Core/Utilities.js"]],function(a,l){l=l.extend;var h={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},
text:"-",y:28}},mouseWheelSensitivity:1.1};l(a.defaultOptions.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});return a.defaultOptions.mapNavigation=h});w(a,"Maps/MapNavigation.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,l,m){function h(b){b&&(b.preventDefault&&b.preventDefault(),b.stopPropagation&&b.stopPropagation(),b.cancelBubble=!0)}function v(b){this.init(b)}var u=l.doc,k=m.addEvent,d=m.extend,g=m.merge,c=m.objectEach,f=m.pick;v.prototype.init=function(b){this.chart=
b;b.mapNavButtons=[]};v.prototype.update=function(b){var a=this.chart,n=a.options.mapNavigation,q,m,z,x,l=function(b){this.handler.call(a,b);h(b)},t=a.mapNavButtons;b&&(n=a.options.mapNavigation=g(a.options.mapNavigation,b));for(;t.length;)t.pop().destroy();f(n.enableButtons,n.enabled)&&!a.renderer.forExport&&c(n.buttons,function(b,c){b=g(n.buttonOptions,b);!a.styledMode&&b.theme&&(q=b.theme,q.style=g(b.theme.style,b.style),z=(m=q.states)&&m.hover,x=m&&m.select,delete q.states);var e=a.renderer.button(b.text||
"",0,0,l,q,z,x,void 0,"zoomIn"===c?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[c]).attr({width:b.width,height:b.height,title:a.options.lang[c],padding:b.padding,zIndex:5}).add();e.handler=b.onclick;k(e.element,"dblclick",h);t.push(e);d(b,{width:e.width,height:2*e.height});if(a.hasLoaded)e.align(b,!1,b.alignTo);else var f=k(a,"load",function(){e.element&&e.align(b,!1,b.alignTo);f()})});this.updateEvents(n)};v.prototype.updateEvents=
function(b){var c=this.chart;f(b.enableDoubleClickZoom,b.enabled)||b.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||k(c.container,"dblclick",function(b){c.pointer.onContainerDblClick(b)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());f(b.enableMouseWheelZoom,b.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||k(c.container,void 0!==u.onwheel?"wheel":void 0!==u.onmousewheel?"mousewheel":"DOMMouseScroll",function(b){c.pointer.inClass(b.target,"highcharts-no-mousewheel")||
(c.pointer.onContainerMouseWheel(b),h(b));return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};d(a.prototype,{fitToBox:function(b,c){[["x","width"],["y","height"]].forEach(function(a){var d=a[0];a=a[1];b[d]+b[a]>c[d]+c[a]&&(b[a]>c[a]?(b[a]=c[a],b[d]=c[d]):b[d]=c[d]+c[a]-b[a]);b[a]>c[a]&&(b[a]=c[a]);b[d]<c[d]&&(b[d]=c[d])});return b},mapZoom:function(b,c,a,d,g,k){var n=this.xAxis[0],q=n.max-n.min,t=f(c,n.min+q/2),h=q*b;q=this.yAxis[0];var e=q.max-q.min,p=f(a,q.min+e/2);
e*=b;t=this.fitToBox({x:t-h*(d?(d-n.pos)/n.len:.5),y:p-e*(g?(g-q.pos)/q.len:.5),width:h,height:e},{x:n.dataMin,y:q.dataMin,width:n.dataMax-n.dataMin,height:q.dataMax-q.dataMin});h=t.x<=n.dataMin&&t.width>=n.dataMax-n.dataMin&&t.y<=q.dataMin&&t.height>=q.dataMax-q.dataMin;d&&n.mapAxis&&(n.mapAxis.fixTo=[d-n.pos,c]);g&&q.mapAxis&&(q.mapAxis.fixTo=[g-q.pos,a]);"undefined"===typeof b||h?(n.setExtremes(void 0,void 0,!1),q.setExtremes(void 0,void 0,!1)):(n.setExtremes(t.x,t.x+t.width,!1),q.setExtremes(t.y,
t.y+t.height,!1));this.redraw(k)}});k(a,"beforeRender",function(){this.mapNavigation=new v(this);this.mapNavigation.update()});l.MapNavigation=v});w(a,"Maps/MapPointer.js",[a["Core/Pointer.js"],a["Core/Utilities.js"]],function(a,l){var h=l.extend,r=l.pick;l=l.wrap;var v=0,u;h(a.prototype,{onContainerDblClick:function(a){var d=this.chart;a=this.normalize(a);d.options.mapNavigation.enableDoubleClickZoomTo?d.pointer.inClass(a.target,"highcharts-tracker")&&d.hoverPoint&&d.hoverPoint.zoomTo():d.isInsidePlot(a.chartX-
d.plotLeft,a.chartY-d.plotTop)&&d.mapZoom(.5,d.xAxis[0].toValue(a.chartX),d.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var d=this.chart;a=this.normalize(a);var g=a.deltaY||a.detail||-(a.wheelDelta/120);1<=Math.abs(g)&&(v+=Math.abs(g),u&&clearTimeout(u),u=setTimeout(function(){v=0},50));10>v&&d.isInsidePlot(a.chartX-d.plotLeft,a.chartY-d.plotTop)&&d.mapZoom(Math.pow(d.options.mapNavigation.mouseWheelSensitivity,g),d.xAxis[0].toValue(a.chartX),d.yAxis[0].toValue(a.chartY),
a.chartX,a.chartY,1>Math.abs(g)?!1:void 0)}});l(a.prototype,"zoomOption",function(a){var d=this.chart.options.mapNavigation;r(d.enableTouchZoom,d.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});l(a.prototype,"pinchTranslate",function(a,d,g,c,f,b,h){a.call(this,d,g,c,f,b,h);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=c.scaleX>c.scaleY,this.pinchTranslateDirection(!a,d,g,c,f,b,h,a?c.scaleX:c.scaleY))})});w(a,"Maps/MapSymbols.js",[a["Core/Renderer/SVG/SVGRenderer.js"]],
function(a){function h(a,h,l,u,k,d,g,c){return[["M",a+k,h],["L",a+l-d,h],["C",a+l-d/2,h,a+l,h+d/2,a+l,h+d],["L",a+l,h+u-g],["C",a+l,h+u-g/2,a+l-g/2,h+u,a+l-g,h+u],["L",a+c,h+u],["C",a+c/2,h+u,a,h+u-c/2,a,h+u-c],["L",a,h+k],["C",a,h+k/2,a+k/2,h,a+k,h],["Z"]]}a=a.prototype.symbols;a.bottombutton=function(a,l,v,u,k){k=k&&k.r||0;return h(a-1,l-1,v,u,0,0,k,k)};a.topbutton=function(a,l,v,u,k){k=k&&k.r||0;return h(a-1,l-1,v,u,k,k,0,0)};return a});w(a,"Core/Chart/MapChart.js",[a["Core/Chart/Chart.js"],a["Core/DefaultOptions.js"],
a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,l,m,r){var h=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,d)};return function(c,d){function b(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(b.prototype=d.prototype,new b)}}(),u=l.getOptions,k=r.merge,d=r.pick;a=function(a){function c(){return null!==
a&&a.apply(this,arguments)||this}h(c,a);c.prototype.init=function(c,b){var f={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},g=u().credits;c=k({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:d(g.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:d(g.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:f,yAxis:k(f,{reversed:!0})},c,{chart:{inverted:!1,alignTicks:!1}});a.prototype.init.call(this,c,b)};
return c}(a);(function(a){a.maps={};a.mapChart=function(c,d,b){return new a(c,d,b)};a.splitPath=function(a){"string"===typeof a&&(a=a.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),a=a.split(/[ ,;]+/).map(function(a){return/[A-za-z]/.test(a)?a:parseFloat(a)}));return m.prototype.pathToSegments(a)}})(a||(a={}));return a});w(a,"Series/Map/MapPoint.js",[a["Mixins/ColorMapSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,l,m){var h=this&&this.__extends||
function(){var a=function(k,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(k,d)};return function(k,d){function g(){this.constructor=k}a(k,d);k.prototype=null===d?Object.create(d):(g.prototype=d.prototype,new g)}}();a=a.colorMapPointMixin;var v=m.extend;l=function(a){function k(){var d=null!==a&&a.apply(this,arguments)||this;d.options=void 0;d.path=void 0;d.series=void 0;return d}h(k,
a);k.prototype.applyOptions=function(d,g){var c=this.series;d=a.prototype.applyOptions.call(this,d,g);g=c.joinBy;c.mapData&&c.mapMap&&(g=a.prototype.getNestedProperty.call(d,g[1]),(g="undefined"!==typeof g&&c.mapMap[g])?(c.xyFromShape&&(d.x=g._midX,d.y=g._midY),v(d,g)):d.value=d.value||null);return d};k.prototype.onMouseOver=function(d){m.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)a.prototype.onMouseOver.call(this,d);else this.series.onMouseOut(d)};
k.prototype.zoomTo=function(){var a=this.series;a.xAxis.setExtremes(this._minX,this._maxX,!1);a.yAxis.setExtremes(this._minY,this._maxY,!1);a.chart.redraw()};return k}(l.seriesTypes.scatter.prototype.pointClass);v(l.prototype,{dataLabelOnNull:a.dataLabelOnNull,isValid:a.isValid,moveToTopOnHover:a.moveToTopOnHover});return l});w(a,"Series/Map/MapSeries.js",[a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Core/Legend/LegendSymbol.js"],a["Core/Chart/MapChart.js"],a["Series/Map/MapPoint.js"],a["Core/Color/Palette.js"],
a["Core/Series/Series.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,l,m,r,v,u,k,d,g,c){var f=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,
new d)}}();a=a.colorMapSeriesMixin;var b=l.noop,h=r.maps,n=r.splitPath;r=d.seriesTypes;var q=r.column,E=r.scatter;r=c.extend;var z=c.fireEvent,x=c.getNestedProperty,D=c.isArray,t=c.isNumber,C=c.merge,e=c.objectEach,p=c.pick,B=c.splat;c=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.baseTrans=void 0;b.chart=void 0;b.data=void 0;b.group=void 0;b.joinBy=void 0;b.options=void 0;b.points=void 0;b.transformGroup=void 0;return b}f(b,a);b.prototype.animate=function(a){var b=this.options.animation,
c=this.group,d=this.xAxis,e=this.yAxis,f=d.pos,g=e.pos;this.chart.renderer.isSVG&&(!0===b&&(b={duration:1E3}),a?c.attr({translateX:f+d.len/2,translateY:g+e.len/2,scaleX:.001,scaleY:.001}):c.animate({translateX:f,translateY:g,scaleX:1,scaleY:1},b))};b.prototype.animateDrilldown=function(a){var b=this.chart.plotBox,c=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],d=c.bBox,e=this.chart.options.drilldown.animation;a||(a=Math.min(d.width/b.width,d.height/b.height),c.shapeArgs={scaleX:a,
scaleY:a,translateX:d.x,translateY:d.y},this.points.forEach(function(a){a.graphic&&a.graphic.attr(c.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},e)}))};b.prototype.animateDrillupFrom=function(a){q.prototype.animateDrillupFrom.call(this,a)};b.prototype.animateDrillupTo=function(a){q.prototype.animateDrillupTo.call(this,a)};b.prototype.doFullTranslate=function(){return this.isDirtyData||this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans};b.prototype.drawMapDataLabels=
function(){k.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};b.prototype.drawPoints=function(){var a=this,b=a.xAxis,c=a.yAxis,d=a.group,e=a.chart,f=e.renderer,g=this.baseTrans;a.transformGroup||(a.transformGroup=f.g().attr({scaleX:1,scaleY:1}).add(d),a.transformGroup.survive=!0);if(a.doFullTranslate())e.hasRendered&&!e.styledMode&&a.points.forEach(function(b){b.shapeArgs&&(b.shapeArgs.fill=a.pointAttribs(b,b.state).fill)}),a.group=a.transformGroup,
q.prototype.drawPoints.apply(a),a.group=d,a.points.forEach(function(b){if(b.graphic){var c="";b.name&&(c+="highcharts-name-"+b.name.replace(/ /g,"-").toLowerCase());b.properties&&b.properties["hc-key"]&&(c+=" highcharts-key-"+b.properties["hc-key"].toLowerCase());c&&b.graphic.addClass(c);e.styledMode&&b.graphic.css(a.pointAttribs(b,b.selected&&"select"||void 0))}}),this.baseTrans={originX:b.min-b.minPixelPadding/b.transA,originY:c.min-c.minPixelPadding/c.transA+(c.reversed?0:c.len/c.transA),transAX:b.transA,
transAY:c.transA},this.transformGroup.animate({translateX:0,translateY:0,scaleX:1,scaleY:1});else{var k=b.transA/g.transAX;var t=c.transA/g.transAY;var n=b.toPixels(g.originX,!0);var h=c.toPixels(g.originY,!0);.99<k&&1.01>k&&.99<t&&1.01>t&&(t=k=1,n=Math.round(n),h=Math.round(h));var l=this.transformGroup;if(e.renderer.globalAnimation){var x=l.attr("translateX");var z=l.attr("translateY");var C=l.attr("scaleX");var A=l.attr("scaleY");l.attr({animator:0}).animate({animator:1},{step:function(a,b){l.attr({translateX:x+
(n-x)*b.pos,translateY:z+(h-z)*b.pos,scaleX:C+(k-C)*b.pos,scaleY:A+(t-A)*b.pos})}})}else l.attr({translateX:n,translateY:h,scaleX:k,scaleY:t})}e.styledMode||d.element.setAttribute("stroke-width",p(a.options[a.pointAttrToOptions&&a.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(k||1));this.drawMapDataLabels()};b.prototype.getBox=function(a){var b=Number.MAX_VALUE,c=-b,d=b,e=-b,f=b,k=b,t=this.xAxis,q=this.yAxis,h;(a||[]).forEach(function(a){if(a.path){"string"===typeof a.path?a.path=n(a.path):
"M"===a.path[0]&&(a.path=g.prototype.pathToSegments(a.path));var t=a.path||[],q=-b,y=b,l=-b,x=b,z=a.properties;a._foundBox||(t.forEach(function(a){var b=a[a.length-2];a=a[a.length-1];"number"===typeof b&&"number"===typeof a&&(y=Math.min(y,b),q=Math.max(q,b),x=Math.min(x,a),l=Math.max(l,a))}),a._midX=y+(q-y)*p(a.middleX,z&&z["hc-middle-x"],.5),a._midY=x+(l-x)*p(a.middleY,z&&z["hc-middle-y"],.5),a._maxX=q,a._minX=y,a._maxY=l,a._minY=x,a.labelrank=p(a.labelrank,(q-y)*(l-x)),a._foundBox=!0);c=Math.max(c,
a._maxX);d=Math.min(d,a._minX);e=Math.max(e,a._maxY);f=Math.min(f,a._minY);k=Math.min(a._maxX-a._minX,a._maxY-a._minY,k);h=!0}});h&&(this.minY=Math.min(f,p(this.minY,b)),this.maxY=Math.max(e,p(this.maxY,-b)),this.minX=Math.min(d,p(this.minX,b)),this.maxX=Math.max(c,p(this.maxX,-b)),t&&"undefined"===typeof t.options.minRange&&(t.minRange=Math.min(5*k,(this.maxX-this.minX)/5,t.minRange||b)),q&&"undefined"===typeof q.options.minRange&&(q.minRange=Math.min(5*k,(this.maxY-this.minY)/5,q.minRange||b)))};
b.prototype.getExtremes=function(){var a=k.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);t(b)&&(this.valueMin=b);t(a)&&(this.valueMax=a);return{dataMin:this.minY,dataMax:this.maxY}};b.prototype.hasData=function(){return!!this.processedXData.length};b.prototype.pointAttribs=function(a,b){b=a.series.chart.styledMode?this.colorAttribs(a):q.prototype.pointAttribs.call(this,a,b);b["stroke-width"]=p(a.options[this.pointAttrToOptions&&
this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return b};b.prototype.render=function(){var a=this,b=k.prototype.render;a.chart.renderer.isVML&&3E3<a.data.length?setTimeout(function(){b.call(a)}):b.call(a)};b.prototype.setData=function(a,b,c,d){var f=this.options,g=this.chart.options.chart,p=g&&g.map,q=f.mapData,n=this.joinBy,z=f.keys||this.pointArrayMap,y=[],A={},B=this.chart.mapTransforms;!q&&p&&(q="string"===typeof p?h[p]:p);a&&a.forEach(function(b,c){var d=0;if(t(b))a[c]={value:b};
else if(D(b)){a[c]={};!f.keys&&b.length>z.length&&"string"===typeof b[0]&&(a[c]["hc-key"]=b[0],++d);for(var e=0;e<z.length;++e,++d)z[e]&&"undefined"!==typeof b[d]&&(0<z[e].indexOf(".")?v.prototype.setNestedProperty(a[c],b[d],z[e]):a[c][z[e]]=b[d])}n&&"_i"===n[0]&&(a[c]._i=c)});this.getBox(a);(this.chart.mapTransforms=B=g.mapTransforms||q&&q["hc-transform"]||B)&&e(B,function(a){a.rotation&&(a.cosAngle=Math.cos(a.rotation),a.sinAngle=Math.sin(a.rotation))});if(q){"FeatureCollection"===q.type&&(this.mapTitle=
q.title,q=l.geojson(q,this.type,this));this.mapData=q;this.mapMap={};for(B=0;B<q.length;B++)g=q[B],p=g.properties,g._i=B,n[0]&&p&&p[n[0]]&&(g[n[0]]=p[n[0]]),A[g[n[0]]]=g;this.mapMap=A;if(a&&n[1]){var u=n[1];a.forEach(function(a){a=x(u,a);A[a]&&y.push(A[a])})}if(f.allAreas){this.getBox(q);a=a||[];if(n[1]){var m=n[1];a.forEach(function(a){y.push(x(m,a))})}y="|"+y.map(function(a){return a&&a[n[0]]}).join("|")+"|";q.forEach(function(b){n[0]&&-1!==y.indexOf("|"+b[n[0]]+"|")||(a.push(C(b,{value:null})),
d=!1)})}else this.getBox(y)}k.prototype.setData.call(this,a,b,c,d)};b.prototype.setOptions=function(a){a=k.prototype.setOptions.call(this,a);var b=a.joinBy;null===b&&(b="_i");b=this.joinBy=B(b);b[1]||(b[1]=b[0]);return a};b.prototype.translate=function(){var a=this,b=a.xAxis,c=a.yAxis,d=a.doFullTranslate();a.generatePoints();a.data.forEach(function(e){t(e._midX)&&t(e._midY)&&(e.plotX=b.toPixels(e._midX,!0),e.plotY=c.toPixels(e._midY,!0));d&&(e.shapeType="path",e.shapeArgs={d:a.translatePath(e.path)})});
z(a,"afterTranslate")};b.prototype.translatePath=function(a){var b=this.xAxis,c=this.yAxis,e=b.min,d=b.transA,g=b.minPixelPadding,f=c.min,p=c.transA,q=c.minPixelPadding,n=[];a&&a.forEach(function(a){"M"===a[0]?n.push(["M",(a[1]-(e||0))*d+g,(a[2]-(f||0))*p+q]):"L"===a[0]?n.push(["L",(a[1]-(e||0))*d+g,(a[2]-(f||0))*p+q]):"C"===a[0]?n.push(["C",(a[1]-(e||0))*d+g,(a[2]-(f||0))*p+q,(a[3]-(e||0))*d+g,(a[4]-(f||0))*p+q,(a[5]-(e||0))*d+g,(a[6]-(f||0))*p+q]):"Q"===a[0]?n.push(["Q",(a[1]-(e||0))*d+g,(a[2]-
(f||0))*p+q,(a[3]-(e||0))*d+g,(a[4]-(f||0))*p+q]):"Z"===a[0]&&n.push(["Z"])});return n};b.defaultOptions=C(E.defaultOptions,{animation:!1,dataLabels:{crop:!1,formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.value;return t(b)?a(b,-1):""},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:u.neutralColor3,stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:u.neutralColor20,
borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:u.neutralColor20},inactive:{opacity:1}}});return b}(E);r(c.prototype,{type:"map",axisTypes:a.axisTypes,colorAttribs:a.colorAttribs,colorKey:a.colorKey,directTouch:!0,drawDataLabels:b,drawGraph:b,drawLegendSymbol:m.drawRectangle,forceDL:!0,getExtremesFromAll:!0,getSymbol:a.getSymbol,parallelArrays:a.parallelArrays,pointArrayMap:a.pointArrayMap,pointClass:v,preserveAspectRatio:!0,searchPoint:b,
trackerGroups:a.trackerGroups,useMapGeometry:!0});d.registerSeriesType("map",c);"";return c});w(a,"Series/MapLine/MapLineSeries.js",[a["Series/Map/MapSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,l,m){var h=this&&this.__extends||function(){var a=function(d,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(d,c)};return function(d,c){function f(){this.constructor=
d}a(d,c);d.prototype=null===c?Object.create(c):(f.prototype=c.prototype,new f)}}(),v=l.series,u=m.extend,k=m.merge;m=function(d){function g(){var a=null!==d&&d.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(g,d);g.prototype.pointAttribs=function(c,d){c=a.prototype.pointAttribs.call(this,c,d);c.fill=this.options.fillColor;return c};g.defaultOptions=k(a.defaultOptions,{lineWidth:1,fillColor:"none"});return g}(a);u(m.prototype,{type:"mapline",colorProp:"stroke",
drawLegendSymbol:v.prototype.drawLegendSymbol,pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"}});l.registerSeriesType("mapline",m);"";return m});w(a,"Series/MapPoint/MapPointPoint.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,l){var h=this&&this.__extends||function(){var a=function(h,k){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var c in g)g.hasOwnProperty(c)&&(a[c]=g[c])};return a(h,k)};return function(h,
k){function d(){this.constructor=h}a(h,k);h.prototype=null===k?Object.create(k):(d.prototype=k.prototype,new d)}}(),r=l.merge;return function(a){function l(){var k=null!==a&&a.apply(this,arguments)||this;k.options=void 0;k.series=void 0;return k}h(l,a);l.prototype.applyOptions=function(k,d){k="undefined"!==typeof k.lat&&"undefined"!==typeof k.lon?r(k,this.series.chart.fromLatLonToPoint(k)):k;return a.prototype.applyOptions.call(this,k,d)};return l}(a.seriesTypes.scatter.prototype.pointClass)});w(a,
"Series/MapPoint/MapPointSeries.js",[a["Series/MapPoint/MapPointPoint.js"],a["Core/Color/Palette.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,l,m,r){var h=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,d)};return function(c,d){function b(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):
(b.prototype=d.prototype,new b)}}(),u=m.seriesTypes.scatter,k=r.extend,d=r.merge;r=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}h(c,a);c.prototype.drawDataLabels=function(){a.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};c.defaultOptions=d(u.defaultOptions,{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:l.neutralColor100}}});
return c}(u);k(r.prototype,{type:"mappoint",forceDL:!0,pointClass:a});m.registerSeriesType("mappoint",r);"";return r});w(a,"Series/Bubble/BubbleLegendDefaults.js",[a["Core/Color/Palette.js"]],function(a){return{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:"10px",color:a.neutralColor100},
x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}});w(a,"Series/Bubble/BubbleLegendItem.js",[a["Core/Color/Color.js"],a["Core/FormatUtilities.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,l,m,r){var h=a.parse,u=m.noop,k=r.arrayMax,d=r.arrayMin,g=r.isNumber,c=r.merge,f=r.pick,b=r.stableSort;"";return function(){function a(a,b){this.options=this.symbols=this.visible=
this.selected=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=u;this.init(a,b)}a.prototype.init=function(a,b){this.options=a;this.visible=!0;this.chart=b.chart;this.legend=b};a.prototype.addToLegend=function(a){a.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(a){var c=this.chart,d=this.options,k=f(a.options.itemDistance,
20),n=d.ranges,h=d.connectorDistance;this.fontMetrics=c.renderer.fontMetrics(d.labels.style.fontSize);n&&n.length&&g(n[0].value)?(b(n,function(a,b){return b.value-a.value}),this.ranges=n,this.setOptions(),this.render(),a=this.getMaxLabelSize(),n=this.ranges[0].radius,c=2*n,h=h-n+a.width,h=0<h?h:0,this.maxLabel=a,this.movementX="left"===d.labels.align?h:0,this.legendItemWidth=c+h+k,this.legendItemHeight=c+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var a=
this.ranges,b=this.options,d=this.chart.series[b.seriesIndex],g=this.legend.baseline,k={zIndex:b.zIndex,"stroke-width":b.borderWidth},l={zIndex:b.zIndex,"stroke-width":b.connectorWidth},t={align:this.legend.options.rtl||"left"===b.labels.align?"right":"left",zIndex:b.zIndex},C=d.options.marker.fillOpacity,e=this.chart.styledMode;a.forEach(function(p,n){e||(k.stroke=f(p.borderColor,b.borderColor,d.color),k.fill=f(p.color,b.color,1!==C?h(d.color).setOpacity(C).get("rgba"):d.color),l.stroke=f(p.connectorColor,
b.connectorColor,d.color));a[n].radius=this.getRangeRadius(p.value);a[n]=c(a[n],{center:a[0].radius-a[n].radius+g});e||c(!0,a[n],{bubbleAttribs:c(k),connectorAttribs:c(l),labelAttribs:t})},this)};a.prototype.getRangeRadius=function(a){var b=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,b.ranges[b.ranges.length-1].value,b.ranges[0].value,b.minSize,b.maxSize,a)};a.prototype.render=function(){var a=this.chart.renderer,b=this.options.zThreshold;this.symbols||(this.symbols=
{connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=b&&this.renderRange(a)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(a){var b=this.options,c=b.labels,d=this.chart,g=d.series[b.seriesIndex],f=d.renderer,k=this.symbols;d=k.labels;
var n=a.center,e=Math.abs(a.radius),p=b.connectorDistance||0,h=c.align,l=b.connectorWidth,m=this.ranges[0].radius||0,y=n-e-b.borderWidth/2+l/2,u=this.fontMetrics;u=u.f/2-(u.h-u.f)/2;var A=f.styledMode;p=this.legend.options.rtl||"left"===h?-p:p;"center"===h&&(p=0,b.connectorDistance=0,a.labelAttribs.align="center");h=y+b.labels.y;var r=m+p+b.labels.x;k.bubbleItems.push(f.circle(m,n+((y%1?1:.5)-(l%2?0:.5)),e).attr(A?{}:a.bubbleAttribs).addClass((A?"highcharts-color-"+g.colorIndex+" ":"")+"highcharts-bubble-legend-symbol "+
(b.className||"")).add(this.legendSymbol));k.connectors.push(f.path(f.crispLine([["M",m,y],["L",m+p,y]],b.connectorWidth)).attr(A?{}:a.connectorAttribs).addClass((A?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(b.connectorClassName||"")).add(this.legendSymbol));a=f.text(this.formatLabel(a),r,h+u).attr(A?{}:a.labelAttribs).css(A?{}:c.style).addClass("highcharts-bubble-legend-labels "+(b.labels.className||"")).add(this.legendSymbol);d.push(a);a.placed=
!0;a.alignAttr={x:r,y:h+u}};a.prototype.getMaxLabelSize=function(){var a,b;this.symbols.labels.forEach(function(c){b=c.getBBox(!0);a=a?b.width>a.width?b:a:b});return a||{}};a.prototype.formatLabel=function(a){var b=this.options,c=b.labels.formatter;b=b.labels.format;var d=this.chart.numberFormatter;return b?l.format(b,a):c?c.call(a):d(a.value,1)};a.prototype.hideOverlappingLabels=function(){var a=this.chart,b=this.symbols;!this.options.labels.allowOverlap&&b&&(a.hideOverlappingLabels(b.labels),b.labels.forEach(function(a,
c){a.newOpacity?a.newOpacity!==a.oldOpacity&&b.connectors[c].show():b.connectors[c].hide()}))};a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,b=a.options.ranges,h,l=Number.MAX_VALUE,x=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(h=a.zData.filter(g),h.length&&(l=f(a.options.zMin,Math.min(l,Math.max(d(h),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),x=f(a.options.zMax,Math.max(x,k(h)))))});var m=l===x?[{value:x}]:[{value:l},
{value:(l+x)/2},{value:x,autoRanges:!0}];b.length&&b[0].radius&&m.reverse();m.forEach(function(a,d){b&&b[d]&&(m[d]=c(b[d],a))});return m};a.prototype.predictBubbleSizes=function(){var a=this.chart,b=this.fontMetrics,c=a.legend.options,d="horizontal"===c.layout,g=d?a.legend.lastLineHeight:0,f=a.plotSizeX,k=a.plotSizeY,h=a.series[this.options.seriesIndex];a=Math.ceil(h.minPxSize);var e=Math.ceil(h.maxPxSize),p=Math.min(k,f);h=h.options.maxSize;if(c.floating||!/%$/.test(h))b=e;else if(h=parseFloat(h),
b=(p+g-b.h/2)*h/100/(h/100+1),d&&k-b>=f||!d&&f-b>=k)b=e;return[a,Math.ceil(b)]};a.prototype.updateRanges=function(a,b){var c=this.legend.options.bubbleLegend;c.minSize=a;c.maxSize=b;c.ranges=this.getRanges()};a.prototype.correctSizes=function(){var a=this.legend,b=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(b.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,b.maxPxSize),a.render())};return a}()});w(a,"Series/Bubble/BubbleLegendComposition.js",[a["Series/Bubble/BubbleLegendDefaults.js"],
a["Series/Bubble/BubbleLegendItem.js"],a["Core/DefaultOptions.js"],a["Core/Utilities.js"]],function(a,l,m,r){var h=m.setOptions,u=r.addEvent,k=r.objectEach,d=r.wrap,g;(function(c){function f(a,c,d){var f=this.legend,h=0<=b(this);if(f&&f.options.enabled&&f.bubbleLegend&&f.options.bubbleLegend.autoRanges&&h){var e=f.bubbleLegend.options;h=f.bubbleLegend.predictBubbleSizes();f.bubbleLegend.updateRanges(h[0],h[1]);e.placed||(f.group.placed=!1,f.allItems.forEach(function(a){a.legendGroup.translateY=null}));
f.render();this.getMargins();this.axes.forEach(function(a){a.visible&&a.render();e.placed||(a.setScale(),a.updateNames(),k(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});e.placed=!0;this.getMargins();a.call(this,c,d);f.bubbleLegend.correctSizes();m(f,g(f))}else a.call(this,c,d),f&&f.options.enabled&&f.bubbleLegend&&(f.render(),m(f,g(f)))}function b(a){a=a.series;for(var b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;b++}return-1}function g(a){a=a.allItems;var b=
[],c=a.length,d,f=0;for(d=0;d<c;d++)if(a[d].legendItemHeight&&(a[d].itemHeight=a[d].legendItemHeight),a[d]===a[c-1]||a[d+1]&&a[d]._legendItemPos[1]!==a[d+1]._legendItemPos[1]){b.push({height:0});var e=b[b.length-1];for(f;f<=d;f++)a[f].itemHeight>e.height&&(e.height=a[f].itemHeight);e.step=d}return b}function n(a){var c=this.bubbleLegend,d=this.options,f=d.bubbleLegend,g=b(this.chart);c&&c.ranges&&c.ranges.length&&(f.ranges.length&&(f.autoRanges=!!f.ranges[0].autoRanges),this.destroyItem(c));0<=g&&
d.enabled&&f.enabled&&(f.seriesIndex=g,this.bubbleLegend=new l(f,this),this.bubbleLegend.addToLegend(a.allItems))}function q(){var a=this.chart,c=this.visible,d=this.chart.legend;d&&d.bubbleLegend&&(this.visible=!c,this.ignoreSeries=c,a=0<=b(a),d.bubbleLegend.visible!==a&&(d.update({bubbleLegend:{enabled:a}}),d.bubbleLegend.visible=a),this.visible=c)}function m(a,b){var c=a.options.rtl,d,f,e,g=0;a.allItems.forEach(function(a,k){d=a.legendGroup.translateX;f=a._legendItemPos[1];if((e=a.movementX)||
c&&a.ranges)e=c?d-a.options.maxSize/2:d+e,a.legendGroup.attr({translateX:e});k>b[g].step&&g++;a.legendGroup.attr({translateY:Math.round(f+b[g].height/2)});a._legendItemPos[1]=f+b[g].height/2})}c.compose=function(b,c,g){h({legend:{bubbleLegend:a}});u(c,"afterGetAllItems",n);u(g,"legendItemClick",q);d(b.prototype,"drawChartBox",f)}})(g||(g={}));return g});w(a,"Series/Bubble/BubblePoint.js",[a["Core/Series/Point.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,l,m){var h=this&&
this.__extends||function(){var a=function(h,k){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var c in g)g.hasOwnProperty(c)&&(a[c]=g[c])};return a(h,k)};return function(h,k){function d(){this.constructor=h}a(h,k);h.prototype=null===k?Object.create(k):(d.prototype=k.prototype,new d)}}();m=m.extend;l=function(l){function m(){var a=null!==l&&l.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}h(m,l);m.prototype.haloPath=function(h){return a.prototype.haloPath.call(this,
0===h?0:(this.marker?this.marker.radius||0:0)+h)};return m}(l.seriesTypes.scatter.prototype.pointClass);m(l.prototype,{ttBelow:!1});return l});w(a,"Series/Bubble/BubbleSeries.js",[a["Core/Axis/Axis.js"],a["Series/Bubble/BubbleLegendComposition.js"],a["Series/Bubble/BubblePoint.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Series/Series.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,l,m,r,v,u,k,d){var g=this&&this.__extends||function(){var a=function(b,c){a=
Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),c=r.parse;r=v.noop;var f=k.seriesTypes;v=f.column;var b=f.scatter,h=d.arrayMax,n=d.arrayMin,q=d.clamp,w=d.extend,z=d.isNumber,x=d.merge,D=d.pick,t=d.pInt;d=function(a){function d(){var b=null!==a&&a.apply(this,
arguments)||this;b.data=void 0;b.maxPxSize=void 0;b.minPxSize=void 0;b.options=void 0;b.points=void 0;b.radii=void 0;b.yData=void 0;b.zData=void 0;return b}g(d,a);d.prototype.animate=function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var b=a.graphic;b&&b.width&&(this.hasRendered||b.attr({x:a.plotX,y:a.plotY,width:1,height:1}),b.animate(this.markerAttribs(a),this.options.animation))},this)};d.prototype.getRadii=function(a,b,c){var d=this.zData,e=this.yData,
f=c.minPxSize,g=c.maxPxSize,h=[];var k=0;for(c=d.length;k<c;k++){var p=d[k];h.push(this.getRadius(a,b,f,g,p,e[k]))}this.radii=h};d.prototype.getRadius=function(a,b,c,d,e,f){var g=this.options,h="width"!==g.sizeBy,k=g.zThreshold,p=b-a,l=.5;if(null===f||null===e)return null;if(z(e)){g.sizeByAbsoluteValue&&(e=Math.abs(e-k),p=Math.max(b-k,Math.abs(a-k)),a=0);if(e<a)return c/2-1;0<p&&(l=(e-a)/p)}h&&0<=l&&(l=Math.sqrt(l));return Math.ceil(c+l*(d-c))/2};d.prototype.hasData=function(){return!!this.processedXData.length};
d.prototype.pointAttribs=function(a,b){var d=this.options.marker.fillOpacity;a=u.prototype.pointAttribs.call(this,a,b);1!==d&&(a.fill=c(a.fill).setOpacity(d).get("rgba"));return a};d.prototype.translate=function(){var b,c=this.data,d=this.radii;a.prototype.translate.call(this);for(b=c.length;b--;){var e=c[b];var f=d?d[b]:0;z(f)&&f>=this.minPxSize/2?(e.marker=w(e.marker,{radius:f,width:2*f,height:2*f}),e.dlBox={x:e.plotX-f,y:e.plotY-f,width:2*f,height:2*f}):e.shapeArgs=e.plotY=e.dlBox=void 0}};d.compose=
l.compose;d.defaultOptions=x(b.defaultOptions,{dataLabels:{formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.z;return z(b)?a(b,-1):""},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});
return d}(b);w(d.prototype,{alignDataLabel:v.prototype.alignDataLabel,applyZones:r,bubblePadding:!0,buildKDTree:r,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:m,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});a.prototype.beforePadding=function(){var a=this,b=this.len,c=this.chart,d=0,f=b,g=this.isXAxis,k=g?"xData":"yData",l=this.min,m={},u=Math.min(c.plotWidth,c.plotHeight),A=Number.MAX_VALUE,r=-Number.MAX_VALUE,x=this.max-
l,v=b/x,w=[];this.series.forEach(function(b){var d=b.options;!b.bubblePadding||!b.visible&&c.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,w.push(b),g&&(["minSize","maxSize"].forEach(function(a){var b=d[a],c=/%$/.test(b);b=t(b);m[a]=c?u*b/100:b}),b.minPxSize=m.minSize,b.maxPxSize=Math.max(m.maxSize,m.minSize),b=b.zData.filter(z),b.length&&(A=D(d.zMin,q(n(b),!1===d.displayNegative?d.zThreshold:-Number.MAX_VALUE,A)),r=D(d.zMax,Math.max(r,h(b))))))});w.forEach(function(b){var c=b[k],e=c.length;
g&&b.getRadii(A,r,b);if(0<x)for(;e--;)if(z(c[e])&&a.dataMin<=c[e]&&c[e]<=a.max){var h=b.radii?b.radii[e]:0;d=Math.min((c[e]-l)*v-h,d);f=Math.max((c[e]-l)*v+h,f)}});w.length&&0<x&&!this.logarithmic&&(f-=b,v*=(b+Math.max(0,d)-Math.min(f,b))/b,[["min","userMin",d],["max","userMax",f]].forEach(function(b){"undefined"===typeof D(a.options[b[0]],a[b[1]])&&(a[b[0]]+=b[2]/v)}))};k.registerSeriesType("bubble",d);"";"";return d});w(a,"Series/MapBubble/MapBubblePoint.js",[a["Core/Series/SeriesRegistry.js"],
a["Core/Utilities.js"]],function(a,l){var h=this&&this.__extends||function(){var a=function(d,g){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var b in d)d.hasOwnProperty(b)&&(a[b]=d[b])};return a(d,g)};return function(d,g){function c(){this.constructor=d}a(d,g);d.prototype=null===g?Object.create(g):(c.prototype=g.prototype,new c)}}(),r=a.seriesTypes,v=r.map;a=l.extend;var u=l.merge;l=function(a){function d(){return null!==a&&a.apply(this,
arguments)||this}h(d,a);d.prototype.applyOptions=function(d,c){return d&&"undefined"!==typeof d.lat&&"undefined"!==typeof d.lon?a.prototype.applyOptions.call(this,u(d,this.series.chart.fromLatLonToPoint(d)),c):v.prototype.pointClass.prototype.applyOptions.call(this,d,c)};d.prototype.isValid=function(){return"number"===typeof this.z};return d}(r.bubble.prototype.pointClass);a(l.prototype,{ttBelow:!1});return l});w(a,"Series/MapBubble/MapBubbleSeries.js",[a["Series/Bubble/BubbleSeries.js"],a["Series/MapBubble/MapBubblePoint.js"],
a["Series/Map/MapSeries.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,l,m,r,v){var h=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,d)};return function(c,d){function b(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(b.prototype=d.prototype,new b)}}(),k=v.extend,d=v.merge;v=function(g){function c(){var a=
null!==g&&g.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(c,g);c.defaultOptions=d(a.defaultOptions,{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}});return c}(a);k(v.prototype,{type:"mapbubble",getBox:m.prototype.getBox,pointArrayMap:["z"],pointClass:l,setData:m.prototype.setData,setOptions:m.prototype.setOptions,xyFromShape:!0});r.registerSeriesType("mapbubble",v);"";return v});w(a,"Series/Heatmap/HeatmapPoint.js",[a["Mixins/ColorMapSeries.js"],
a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,l,m){var h=this&&this.__extends||function(){var a=function(d,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(d,c)};return function(d,c){function f(){this.constructor=d}a(d,c);d.prototype=null===c?Object.create(c):(f.prototype=c.prototype,new f)}}();a=a.colorMapPointMixin;var v=m.clamp,u=m.extend,k=m.pick;l=function(a){function d(){var c=
null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.series=void 0;c.value=void 0;c.x=void 0;c.y=void 0;return c}h(d,a);d.prototype.applyOptions=function(c,d){c=a.prototype.applyOptions.call(this,c,d);c.formatPrefix=c.isNull||null===c.value?"null":"point";return c};d.prototype.getCellAttributes=function(){var a=this.series,d=a.options,b=(d.colsize||1)/2,g=(d.rowsize||1)/2,h=a.xAxis,l=a.yAxis,m=this.options.marker||a.options.marker;a=a.pointPlacementToXValue();var u=k(this.pointPadding,d.pointPadding,
0),r={x1:v(Math.round(h.len-(h.translate(this.x-b,!1,!0,!1,!0,-a)||0)),-h.len,2*h.len),x2:v(Math.round(h.len-(h.translate(this.x+b,!1,!0,!1,!0,-a)||0)),-h.len,2*h.len),y1:v(Math.round(l.translate(this.y-g,!1,!0,!1,!0)||0),-l.len,2*l.len),y2:v(Math.round(l.translate(this.y+g,!1,!0,!1,!0)||0),-l.len,2*l.len)};[["width","x"],["height","y"]].forEach(function(a){var b=a[0];a=a[1];var c=a+"1",d=a+"2",f=Math.abs(r[c]-r[d]),g=m&&m.lineWidth||0,h=Math.abs(r[c]+r[d])/2;m[b]&&m[b]<f&&(r[c]=h-m[b]/2-g/2,r[d]=
h+m[b]/2+g/2);u&&("y"===a&&(c=d,d=a+"1"),r[c]+=u,r[d]-=u)});return r};d.prototype.haloPath=function(a){if(!a)return[];var c=this.shapeArgs;return["M",c.x-a,c.y-a,"L",c.x-a,c.y+c.height+a,c.x+c.width+a,c.y+c.height+a,c.x+c.width+a,c.y-a,"Z"]};d.prototype.isValid=function(){return Infinity!==this.value&&-Infinity!==this.value};return d}(l.seriesTypes.scatter.prototype.pointClass);u(l.prototype,{dataLabelOnNull:a.dataLabelOnNull,moveToTopOnHover:a.moveToTopOnHover});return l});w(a,"Series/Heatmap/HeatmapSeries.js",
[a["Core/Color/Color.js"],a["Mixins/ColorMapSeries.js"],a["Series/Heatmap/HeatmapPoint.js"],a["Core/Legend/LegendSymbol.js"],a["Core/Color/Palette.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,l,m,r,v,u,k,d){var g=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,
c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}();l=l.colorMapSeriesMixin;var c=u.series,f=u.seriesTypes,b=f.column,h=f.scatter,n=k.prototype.symbols,q=d.extend,w=d.fireEvent,z=d.isNumber,x=d.merge,D=d.pick;k=function(b){function d(){var a=null!==b&&b.apply(this,arguments)||this;a.colorAxis=void 0;a.data=void 0;a.options=void 0;a.points=void 0;a.valueMax=NaN;a.valueMin=NaN;return a}g(d,b);d.prototype.drawPoints=function(){var a=this;
if((this.options.marker||{}).enabled||this._hasPointMarkers)c.prototype.drawPoints.call(this),this.points.forEach(function(b){b.graphic&&(b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b)),a.options.borderRadius&&b.graphic.attr({r:a.options.borderRadius}),null===b.value&&b.graphic.addClass("highcharts-null-point"))})};d.prototype.getExtremes=function(){var a=c.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;z(b)&&(this.valueMin=b);z(a)&&(this.valueMax=a);return c.prototype.getExtremes.call(this)};
d.prototype.getValidPoints=function(a,b){return c.prototype.getValidPoints.call(this,a,b,!0)};d.prototype.hasData=function(){return!!this.processedXData.length};d.prototype.init=function(){c.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=D(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;n.ellipse=n.circle};d.prototype.markerAttribs=function(a,b){var c=a.marker||{},d=this.options.marker||{},e=a.shapeArgs||{},f={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b){var g=
d.states[b]||{};var h=c.states&&c.states[b]||{};[["width","x"],["height","y"]].forEach(function(a){f[a[0]]=(h[a[0]]||g[a[0]]||e[a[0]])+(h[a[0]+"Plus"]||g[a[0]+"Plus"]||0);f[a[1]]=e[a[1]]+(e[a[0]]-f[a[0]])/2})}return b?f:e};d.prototype.pointAttribs=function(b,d){var e=c.prototype.pointAttribs.call(this,b,d),f=this.options||{},g=this.chart.options.plotOptions||{},h=g.series||{},k=g.heatmap||{};g=b&&b.options.borderColor||f.borderColor||k.borderColor||h.borderColor;h=b&&b.options.borderWidth||f.borderWidth||
k.borderWidth||h.borderWidth||e["stroke-width"];e.stroke=b&&b.marker&&b.marker.lineColor||f.marker&&f.marker.lineColor||g||this.color;e["stroke-width"]=h;d&&(b=x(f.states[d],f.marker&&f.marker.states[d],b&&b.options.states&&b.options.states[d]||{}),d=b.brightness,e.fill=b.color||a.parse(e.fill).brighten(d||0).get(),e.stroke=b.lineColor);return e};d.prototype.setClip=function(a){var b=this.chart;c.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&
this.sharedClipKey?b.sharedClips[this.sharedClipKey]:b.clipRect)};d.prototype.translate=function(){var a=this.options,b=a.marker&&a.marker.symbol||"rect",c=n[b]?b:"rect",d=-1!==["circle","square"].indexOf(c);this.generatePoints();this.points.forEach(function(a){var e=a.getCellAttributes(),f={};f.x=Math.min(e.x1,e.x2);f.y=Math.min(e.y1,e.y2);f.width=Math.max(Math.abs(e.x2-e.x1),0);f.height=Math.max(Math.abs(e.y2-e.y1),0);var g=a.hasImage=0===(a.marker&&a.marker.symbol||b||"").indexOf("url");if(d){var h=
Math.abs(f.width-f.height);f.x=Math.min(e.x1,e.x2)+(f.width<f.height?0:h/2);f.y=Math.min(e.y1,e.y2)+(f.width<f.height?h/2:0);f.width=f.height=Math.min(f.width,f.height)}h={plotX:(e.x1+e.x2)/2,plotY:(e.y1+e.y2)/2,clientX:(e.x1+e.x2)/2,shapeType:"path",shapeArgs:x(!0,f,{d:n[c](f.x,f.y,f.width,f.height)})};g&&(a.marker={width:f.width,height:f.height});q(a,h)});w(this,"afterTranslate")};d.defaultOptions=x(h.defaultOptions,{animation:!1,borderRadius:0,borderWidth:0,nullColor:v.neutralColor3,dataLabels:{formatter:function(){var a=
this.series.chart.numberFormatter,b=this.point.value;return z(b)?a(b,-1):""},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}});return d}(h);q(k.prototype,{alignDataLabel:b.prototype.alignDataLabel,axisTypes:l.axisTypes,colorAttribs:l.colorAttribs,colorKey:l.colorKey,
directTouch:!0,drawLegendSymbol:r.drawRectangle,getExtremesFromAll:!0,getSymbol:c.prototype.getSymbol,parallelArrays:l.parallelArrays,pointArrayMap:["y","value"],pointClass:m,trackerGroups:l.trackerGroups});u.registerSeriesType("heatmap",k);"";"";return k});w(a,"Extensions/GeoJSON.js",[a["Core/Chart/Chart.js"],a["Core/FormatUtilities.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,l,m,r){function h(a,b){var c,d=!1,f=a.x,g=a.y;a=0;for(c=b.length-1;a<b.length;c=a++){var h=b[a][1]>g;var k=
b[c][1]>g;h!==k&&f<(b[c][0]-b[a][0])*(g-b[a][1])/(b[c][1]-b[a][1])+b[a][0]&&(d=!d)}return d}var u=l.format,k=m.win,d=r.error,g=r.extend,c=r.merge;l=r.wrap;"";a.prototype.transformFromLatLon=function(a,b){var c=this.userOptions.chart&&this.userOptions.chart.proj4||k.proj4;if(!c)return d(21,!1,this),{x:0,y:null};a=c(b.crs,[a.lon,a.lat]);c=b.cosAngle||b.rotation&&Math.cos(b.rotation);var f=b.sinAngle||b.rotation&&Math.sin(b.rotation);a=b.rotation?[a[0]*c+a[1]*f,-a[0]*f+a[1]*c]:a;return{x:((a[0]-(b.xoffset||
0))*(b.scale||1)+(b.xpan||0))*(b.jsonres||1)+(b.jsonmarginX||0),y:(((b.yoffset||0)-a[1])*(b.scale||1)+(b.ypan||0))*(b.jsonres||1)-(b.jsonmarginY||0)}};a.prototype.transformToLatLon=function(a,b){if("undefined"===typeof k.proj4)d(21,!1,this);else{a={x:((a.x-(b.jsonmarginX||0))/(b.jsonres||1)-(b.xpan||0))/(b.scale||1)+(b.xoffset||0),y:((-a.y-(b.jsonmarginY||0))/(b.jsonres||1)+(b.ypan||0))/(b.scale||1)+(b.yoffset||0)};var c=b.cosAngle||b.rotation&&Math.cos(b.rotation),f=b.sinAngle||b.rotation&&Math.sin(b.rotation);
b=k.proj4(b.crs,"WGS84",b.rotation?{x:a.x*c+a.y*-f,y:a.x*f+a.y*c}:a);return{lat:b.y,lon:b.x}}};a.prototype.fromPointToLatLon=function(a){var b=this.mapTransforms,c;if(b){for(c in b)if(Object.hasOwnProperty.call(b,c)&&b[c].hitZone&&h({x:a.x,y:-a.y},b[c].hitZone.coordinates[0]))return this.transformToLatLon(a,b[c]);return this.transformToLatLon(a,b["default"])}d(22,!1,this)};a.prototype.fromLatLonToPoint=function(a){var b=this.mapTransforms,c;if(!b)return d(22,!1,this),{x:0,y:null};for(c in b)if(Object.hasOwnProperty.call(b,
c)&&b[c].hitZone){var f=this.transformFromLatLon(a,b[c]);if(h({x:f.x,y:-f.y},b[c].hitZone.coordinates[0]))return f}return this.transformFromLatLon(a,b["default"])};m.geojson=function(a,b,c){var d=[],f=[],h=function(a){a.forEach(function(a,b){0===b?f.push(["M",a[0],-a[1]]):f.push(["L",a[0],-a[1]])})};b=b||"map";a.features.forEach(function(a){var c=a.geometry,k=c.type;c=c.coordinates;a=a.properties;var l;f=[];"map"===b||"mapbubble"===b?("Polygon"===k?(c.forEach(h),f.push(["Z"])):"MultiPolygon"===k&&
(c.forEach(function(a){a.forEach(h)}),f.push(["Z"])),f.length&&(l={path:f})):"mapline"===b?("LineString"===k?h(c):"MultiLineString"===k&&c.forEach(h),f.length&&(l={path:f})):"mappoint"===b&&"Point"===k&&(l={x:c[0],y:-c[1]});l&&d.push(g(l,{name:a.name||a.NAME,properties:a}))});c&&a.copyrightShort&&(c.chart.mapCredits=u(c.chart.options.credits.mapText,{geojson:a}),c.chart.mapCreditsFull=u(c.chart.options.credits.mapTextFull,{geojson:a}));return d};l(a.prototype,"addCredits",function(a,b){b=c(!0,this.options.credits,
b);this.mapCredits&&(b.href=null);a.call(this,b);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});w(a,"masters/modules/map.src.js",[a["Core/Globals.js"],a["Core/Axis/Color/ColorAxis.js"],a["Core/Chart/MapChart.js"]],function(a,l,m){a.ColorAxis=l;a.MapChart=m;a.mapChart=a.Map=m.mapChart;a.maps=m.maps;l.compose(a.Chart,a.Fx,a.Legend,a.Series)})});
//# sourceMappingURL=map.js.map