/*
 Highcharts JS v9.1.2 (2021-08-18)

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(z){e(z);e.Highcharts=z;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function z(e,c,h,d){e.hasOwnProperty(c)||(e[c]=d.apply(null,h))}e=e?e._modules:{};z(e,"Extensions/Pane.js",[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Color/Palette.js"],e["Core/Pointer.js"],
e["Core/Utilities.js"],e["Mixins/CenteredSeries.js"]],function(e,c,h,d,a,t){function m(b,p,a){return Math.sqrt(Math.pow(b-a[0],2)+Math.pow(p-a[1],2))<=a[2]/2}var l=a.addEvent,r=a.extend,x=a.merge,b=a.pick,n=a.splat;e.prototype.collectionsWithUpdate.push("pane");a=function(){function b(b,a){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,
borderColor:h.neutralColor20,backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,h.backgroundColor],[1,h.neutralColor10]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(b,a)}b.prototype.init=function(b,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(b)};b.prototype.setOptions=function(b){this.options=x(this.defaultOptions,this.chart.angular?{background:{}}:void 0,b)};b.prototype.render=function(){var b=this.options,a=this.options.background,
k=this.chart.renderer;this.group||(this.group=k.g("pane-group").attr({zIndex:b.zIndex||0}).add());this.updateCenter();if(a)for(a=n(a),b=Math.max(a.length,this.background.length||0),k=0;k<b;k++)a[k]&&this.axis?this.renderBackground(x(this.defaultBackgroundOptions,a[k]),k):this.background[k]&&(this.background[k]=this.background[k].destroy(),this.background.splice(k,1))};b.prototype.renderBackground=function(b,a){var k="animate",p={"class":"highcharts-pane "+(b.className||"")};this.chart.styledMode||
r(p,{fill:b.backgroundColor,stroke:b.borderColor,"stroke-width":b.borderWidth});this.background[a]||(this.background[a]=this.chart.renderer.path().add(this.group),k="attr");this.background[a][k]({d:this.axis.getPlotBandPath(b.from,b.to,b)}).attr(p)};b.prototype.updateCenter=function(b){this.center=(b||this.axis||{}).center=t.getCenter.call(this)};b.prototype.update=function(b,a){x(!0,this.options,b);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(b){b.pane===this&&(b.pane=
null,b.update({},a))},this)};return b}();e.prototype.getHoverPane=function(b){var a=this,k;b&&a.pane.forEach(function(p){var n=b.chartX-a.plotLeft,y=b.chartY-a.plotTop;m(a.inverted?y:n,a.inverted?n:y,p.center)&&(k=p)});return k};l(e,"afterIsInsidePlot",function(b){this.polar&&(b.isInsidePlot=this.pane.some(function(a){return m(b.x,b.y,a.center)}))});l(d,"beforeGetHoverData",function(a){var k=this.chart;k.polar?(k.hoverPane=k.getHoverPane(a),a.filter=function(n){return n.visible&&!(!a.shared&&n.directTouch)&&
b(n.options.enableMouseTracking,!0)&&(!k.hoverPane||n.xAxis.pane===k.hoverPane)}):k.hoverPane=void 0});l(d,"afterGetHoverData",function(b){var a=this.chart;b.hoverPoint&&b.hoverPoint.plotX&&b.hoverPoint.plotY&&a.hoverPane&&!m(b.hoverPoint.plotX,b.hoverPoint.plotY,a.hoverPane.center)&&(b.hoverPoint=void 0)});c.Pane=a;return c.Pane});z(e,"Core/Axis/RadialAxis.js",[e["Core/Axis/AxisDefaults.js"],e["Core/DefaultOptions.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,c,h,d){var a=c.defaultOptions,
t=h.noop,m=d.addEvent,l=d.correctFloat,r=d.defined,x=d.extend,b=d.fireEvent,n=d.merge,k=d.pick,p=d.relativeLength,y=d.wrap,B;(function(d){function c(){this.autoConnect=this.isCircular&&"undefined"===typeof k(this.userMax,this.options.max)&&l(this.endAngleRad-this.startAngleRad)===l(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)}function u(){var g=this;return function(){if(g.isRadial&&g.tickPositions&&
g.options.labels&&!0!==g.options.labels.allowOverlap)return g.tickPositions.map(function(f){return g.ticks[f]&&g.ticks[f].label}).filter(function(g){return!!g})}}function h(){return t}function f(g,f,b){var q=this.pane.center,v=g.value;if(this.isCircular){if(r(v))g.point&&(a=g.point.shapeArgs||{},a.start&&(v=this.chart.inverted?this.translate(g.point.rectPlotY,!0):g.point.x));else{var a=g.chartX||0;var w=g.chartY||0;v=this.translate(Math.atan2(w-b,a-f)-this.startAngleRad,!0)}g=this.getPosition(v);
a=g.x;w=g.y}else r(v)||(a=g.chartX,w=g.chartY),r(a)&&r(w)&&(b=q[1]+this.chart.plotTop,v=this.translate(Math.min(Math.sqrt(Math.pow(a-f,2)+Math.pow(w-b,2)),q[2]/2)-q[3]/2,!0));return[v,a||0,w||0]}function g(g,f,b){g=this.pane.center;var v=this.chart,q=this.left||0,a=this.top||0,w=k(f,g[2]/2-this.offset);"undefined"===typeof b&&(b=this.horiz?0:this.center&&-this.center[3]/2);b&&(w+=b);this.isCircular||"undefined"!==typeof f?(f=this.chart.renderer.symbols.arc(q+g[0],a+g[1],w,w,{start:this.startAngleRad,
end:this.endAngleRad,open:!0,innerR:0}),f.xBounds=[q+g[0]],f.yBounds=[a+g[1]-w]):(f=this.postTranslate(this.angleRad,w),f=[["M",this.center[0]+v.plotLeft,this.center[1]+v.plotTop],["L",f.x,f.y]]);return f}function v(){this.constructor.prototype.getOffset.call(this);this.chart.axisOffset[this.side]=0}function q(g,f,b){var v=this.chart,q=function(g){if("string"===typeof g){var f=parseInt(g,10);F.test(g)&&(f=f*A/100);return f}return g},a=this.center,w=this.startAngleRad,A=a[2]/2,n=Math.min(this.offset,
0),p=this.left||0,y=this.top||0,F=/%$/,d=this.isCircular,c=k(q(b.outerRadius),A),l=q(b.innerRadius);q=k(q(b.thickness),10);if("polygon"===this.options.gridLineInterpolation)n=this.getPlotLinePath({value:g}).concat(this.getPlotLinePath({value:f,reverse:!0}));else{g=Math.max(g,this.min);f=Math.min(f,this.max);g=this.translate(g);f=this.translate(f);d||(c=g||0,l=f||0);if("circle"!==b.shape&&d)b=w+(g||0),w+=f||0;else{b=-Math.PI/2;w=1.5*Math.PI;var u=!0}c-=n;n=v.renderer.symbols.arc(p+a[0],y+a[1],c,c,
{start:Math.min(b,w),end:Math.max(b,w),innerR:k(l,c-(q-n)),open:u});d&&(d=(w+b)/2,p=p+a[0]+a[2]/2*Math.cos(d),n.xBounds=d>-Math.PI/2&&d<Math.PI/2?[p,v.plotWidth]:[0,p],n.yBounds=[y+a[1]+a[2]/2*Math.sin(d)],n.yBounds[0]+=d>-Math.PI&&0>d||d>Math.PI?-10:10)}return n}function w(g){var f=this,b=this.pane.center,q=this.chart,v=q.inverted,a=g.reverse,w=this.pane.options.background?this.pane.options.background[0]||this.pane.options.background:{},n=w.innerRadius||"0%",A=w.outerRadius||"100%",k=b[0]+q.plotLeft,
y=b[1]+q.plotTop,d=this.height,F=g.isCrosshair;w=b[3]/2;var c=g.value,l;var u=this.getPosition(c);var h=u.x;u=u.y;F&&(u=this.getCrosshairPosition(g,k,y),c=u[0],h=u[1],u=u[2]);if(this.isCircular)c=Math.sqrt(Math.pow(h-k,2)+Math.pow(u-y,2)),a="string"===typeof n?p(n,1):n/c,q="string"===typeof A?p(A,1):A/c,b&&w&&(w/=c,a<w&&(a=w),q<w&&(q=w)),b=[["M",k+a*(h-k),y-a*(y-u)],["L",h-(1-q)*(h-k),u+(1-q)*(y-u)]];else if((c=this.translate(c))&&(0>c||c>d)&&(c=0),"circle"===this.options.gridLineInterpolation)b=
this.getLinePath(0,c,w);else if(b=[],q[v?"yAxis":"xAxis"].forEach(function(g){g.pane===f.pane&&(l=g)}),l)for(k=l.tickPositions,l.autoConnect&&(k=k.concat([k[0]])),a&&(k=k.slice().reverse()),c&&(c+=w),y=0;y<k.length;y++)w=l.getPosition(k[y],c),b.push(y?["L",w.x,w.y]:["M",w.x,w.y]);return b}function A(g,f){g=this.translate(g);return this.postTranslate(this.isCircular?g:this.angleRad,k(this.isCircular?f:0>g?0:g,this.center[2]/2)-this.offset)}function F(){var g=this.center,f=this.chart,b=this.options.title;
return{x:f.plotLeft+g[0]+(b.x||0),y:f.plotTop+g[1]-{high:.5,middle:.25,low:0}[b.align]*g[2]+(b.y||0)}}function G(b){b.beforeSetTickPositions=c;b.createLabelCollector=u;b.getCrosshairPosition=f;b.getLinePath=g;b.getOffset=v;b.getPlotBandPath=q;b.getPlotLinePath=w;b.getPosition=A;b.getTitlePosition=F;b.postTranslate=M;b.setAxisSize=E;b.setAxisTranslation=z;b.setOptions=N}function B(){var g=this.chart,f=this.options,b=this.pane,q=b&&b.options;g.angular&&this.isXAxis||!b||!g.angular&&!g.polar||(this.angleRad=
(f.angle||0)*Math.PI/180,this.startAngleRad=(q.startAngle-90)*Math.PI/180,this.endAngleRad=(k(q.endAngle,q.startAngle+360)-90)*Math.PI/180,this.offset=f.offset||0)}function O(g){this.isRadial&&(g.align=void 0,g.preventDefault())}function P(){if(this.chart&&this.chart.labelCollectors){var g=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=g&&this.chart.labelCollectors.splice(g,1)}}function J(g){var b=this.chart,f=b.inverted,q=b.angular,v=b.polar,a=this.isXAxis,w=this.coll,
k=q&&a,A=b.options;g=g.userOptions.pane||0;g=this.pane=b.pane&&b.pane[g];var p;if("colorAxis"===w)this.isRadial=!1;else{if(q){if(k?(this.isHidden=!0,this.createLabelCollector=h,this.getOffset=t,this.render=this.redraw=Q,this.setTitle=this.setCategories=this.setScale=t):G(this),p=!a)this.defaultPolarOptions=R}else v&&(G(this),this.defaultPolarOptions=(p=this.horiz)?S:n("xAxis"===w?e.defaultXAxisOptions:e.defaultYAxisOptions,T),f&&"yAxis"===w&&(this.defaultPolarOptions.stackLabels=e.defaultYAxisOptions.stackLabels,
this.defaultPolarOptions.reversedStacks=!0));q||v?(this.isRadial=!0,A.chart.zoomType=null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&b.labelCollectors.push(this.labelCollector)):this.isRadial=!1;g&&p&&(g.axis=this);this.isCircular=p}}function C(){this.isRadial&&this.beforeSetTickPositions()}function D(g){var b=this.label;if(b){var f=this.axis,q=b.getBBox(),v=f.options.labels,a=(f.translate(this.pos)+f.startAngleRad+Math.PI/2)/Math.PI*180%360,w=Math.round(a),
n=r(v.y)?0:.3*-q.height,A=v.y,y=20,c=v.align,d="end",F=0>w?w+360:w,u=F,l=0,h=0;if(f.isRadial){var m=f.getPosition(this.pos,f.center[2]/2+p(k(v.distance,-25),f.center[2]/2,-f.center[2]/2));"auto"===v.rotation?b.attr({rotation:a}):r(A)||(A=f.chart.renderer.fontMetrics(b.styles&&b.styles.fontSize).b-q.height/2);r(c)||(f.isCircular?(q.width>f.len*f.tickInterval/(f.max-f.min)&&(y=0),c=a>y&&a<180-y?"left":a>180+y&&a<360-y?"right":"center"):c="center",b.attr({align:c}));if("auto"===c&&2===f.tickPositions.length&&
f.isCircular){90<F&&180>F?F=180-F:270<F&&360>=F&&(F=540-F);180<u&&360>=u&&(u=360-u);if(f.pane.options.startAngle===w||f.pane.options.startAngle===w+360||f.pane.options.startAngle===w-360)d="start";c=-90<=w&&90>=w||-360<=w&&-270>=w||270<=w&&360>=w?"start"===d?"right":"left":"start"===d?"left":"right";70<u&&110>u&&(c="center");15>F||180<=F&&195>F?l=.3*q.height:15<=F&&35>=F?l="start"===d?0:.75*q.height:195<=F&&215>=F?l="start"===d?.75*q.height:0:35<F&&90>=F?l="start"===d?.25*-q.height:q.height:215<F&&
270>=F&&(l="start"===d?q.height:.25*-q.height);15>u?h="start"===d?.15*-q.height:.15*q.height:165<u&&180>=u&&(h="start"===d?.15*q.height:.15*-q.height);b.attr({align:c});b.translate(h,l+n)}g.pos.x=m.x+(v.x||0);g.pos.y=m.y+(A||0)}}}function U(g){this.axis.getPosition&&x(g.pos,this.axis.getPosition(this.pos))}function M(g,f){var b=this.chart,q=this.center;g=this.startAngleRad+g;return{x:b.plotLeft+q[0]+Math.cos(g)*f,y:b.plotTop+q[1]+Math.sin(g)*f}}function Q(){this.isDirty=!1}function E(){this.constructor.prototype.setAxisSize.call(this);
if(this.isRadial){this.pane.updateCenter(this);var g=this.center=this.pane.center.slice();if(this.isCircular)this.sector=this.endAngleRad-this.startAngleRad;else{var f=this.postTranslate(this.angleRad,g[3]/2);g[0]=f.x-this.chart.plotLeft;g[1]=f.y-this.chart.plotTop}this.len=this.width=this.height=(g[2]-g[3])*k(this.sector,1)/2}}function z(){this.constructor.prototype.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):
(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)}function N(g){g=this.options=n(this.constructor.defaultOptions,this.defaultPolarOptions,a[this.coll],g);g.plotBands||(g.plotBands=[]);b(this,"afterSetOptions")}function V(g,f,b,q,v,a,w){var k=this.axis;k.isRadial?(g=k.getPosition(this.pos,k.center[2]/2+q),f=["M",f,b,"L",g.x,g.y]):f=g.call(this,f,b,q,v,a,w);return f}var L=[],S={gridLineWidth:1,labels:{align:void 0,distance:15,
x:0,y:void 0,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},R={labels:{align:"center",x:0,y:void 0},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},T={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};d.compose=function(g,f){-1===L.indexOf(g)&&
(L.push(g),m(g,"afterInit",B),m(g,"autoLabelAlign",O),m(g,"destroy",P),m(g,"init",J),m(g,"initialAxisTranslation",C));-1===L.indexOf(f)&&(L.push(f),m(f,"afterGetLabelPosition",D),m(f,"afterGetPosition",U),y(f.prototype,"getMarkPath",V));return g}})(B||(B={}));return B});z(e,"Series/AreaRange/AreaRangePoint.js",[e["Series/Area/AreaSeries.js"],e["Core/Series/Point.js"],e["Core/Utilities.js"]],function(e,c,h){var d=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(b,a){b.__proto__=a}||function(b,a){for(var k in a)a.hasOwnProperty(k)&&(b[k]=a[k])};return a(c,d)};return function(c,d){function b(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(b.prototype=d.prototype,new b)}}(),a=c.prototype,t=h.defined,m=h.isNumber;return function(c){function l(){var a=null!==c&&c.apply(this,arguments)||this;a.high=void 0;a.low=void 0;a.options=void 0;a.plotHigh=void 0;a.plotLow=void 0;a.plotHighX=void 0;a.plotLowX=void 0;a.plotX=void 0;a.series=
void 0;return a}d(l,c);l.prototype.setState=function(){var c=this.state,b=this.series,n=b.chart.polar;t(this.plotHigh)||(this.plotHigh=b.yAxis.toPixels(this.high,!0));t(this.plotLow)||(this.plotLow=this.plotY=b.yAxis.toPixels(this.low,!0));b.stateMarkerGraphic&&(b.lowerStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;n&&(this.plotX=this.plotHighX);a.setState.apply(this,arguments);this.state=c;this.plotY=
this.plotLow;this.graphic=this.lowerGraphic;n&&(this.plotX=this.plotLowX);b.stateMarkerGraphic&&(b.upperStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.lowerStateMarkerGraphic,b.lowerStateMarkerGraphic=void 0);a.setState.apply(this,arguments)};l.prototype.haloPath=function(){var c=this.series.chart.polar,b=[];this.plotY=this.plotLow;c&&(this.plotX=this.plotLowX);this.isInside&&(b=a.haloPath.apply(this,arguments));this.plotY=this.plotHigh;c&&(this.plotX=this.plotHighX);this.isTopInside&&
(b=b.concat(a.haloPath.apply(this,arguments)));return b};l.prototype.isValid=function(){return m(this.low)&&m(this.high)};return l}(e.prototype.pointClass)});z(e,"Series/AreaRange/AreaRangeSeries.js",[e["Series/AreaRange/AreaRangePoint.js"],e["Series/Area/AreaSeries.js"],e["Series/Column/ColumnSeries.js"],e["Core/Globals.js"],e["Core/Series/Series.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h,d,a,t,m){var l=this&&this.__extends||function(){var b=function(a,k){b=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(b,f){b.__proto__=f}||function(b,f){for(var g in f)f.hasOwnProperty(g)&&(b[g]=f[g])};return b(a,k)};return function(a,k){function n(){this.constructor=a}b(a,k);a.prototype=null===k?Object.create(k):(n.prototype=k.prototype,new n)}}(),r=c.prototype,x=h.prototype;h=d.noop;var b=a.prototype,n=m.defined,k=m.extend,p=m.isArray,y=m.pick,B=m.merge;a=function(a){function d(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;
b.lowerStateMarkerGraphic=void 0;b.xAxis=void 0;return b}l(d,a);d.prototype.toYData=function(b){return[b.low,b.high]};d.prototype.highToXY=function(b){var a=this.chart,f=this.xAxis.postTranslate(b.rectPlotX||0,this.yAxis.len-b.plotHigh);b.plotHighX=f.x-a.plotLeft;b.plotHigh=f.y-a.plotTop;b.plotLowX=b.plotX};d.prototype.translate=function(){var b=this,a=b.yAxis,f=!!b.modifyValue;r.translate.apply(b);b.points.forEach(function(g){var v=g.high,q=g.plotY;g.isNull?g.plotY=null:(g.plotLow=q,g.plotHigh=a.translate(f?
b.modifyValue(v,g):v,0,1,0,1),f&&(g.yBottom=g.plotHigh))});this.chart.polar&&this.points.forEach(function(g){b.highToXY(g);g.tooltipPos=[(g.plotHighX+g.plotLowX)/2,(g.plotHigh+g.plotLow)/2]})};d.prototype.getGraphPath=function(b){var a=[],f=[],g,v=r.getGraphPath;var q=this.options;var w=this.chart.polar,k=w&&!1!==q.connectEnds,n=q.connectNulls,c=q.step;b=b||this.points;for(g=b.length;g--;){var p=b[g];var d=w?{plotX:p.rectPlotX,plotY:p.yBottom,doCurve:!1}:{plotX:p.plotX,plotY:p.plotY,doCurve:!1};p.isNull||
k||n||b[g+1]&&!b[g+1].isNull||f.push(d);var l={polarPlotY:p.polarPlotY,rectPlotX:p.rectPlotX,yBottom:p.yBottom,plotX:y(p.plotHighX,p.plotX),plotY:p.plotHigh,isNull:p.isNull};f.push(l);a.push(l);p.isNull||k||n||b[g-1]&&!b[g-1].isNull||f.push(d)}b=v.call(this,b);c&&(!0===c&&(c="left"),q.step={left:"right",center:"center",right:"left"}[c]);a=v.call(this,a);f=v.call(this,f);q.step=c;q=[].concat(b,a);!this.chart.polar&&f[0]&&"M"===f[0][0]&&(f[0]=["L",f[0][1],f[0][2]]);this.graphPath=q;this.areaPath=b.concat(f);
q.isArea=!0;q.xMap=b.xMap;this.areaPath.xMap=b.xMap;return q};d.prototype.drawDataLabels=function(){var a=this.points,n=a.length,f,g=[],v=this.options.dataLabels,q,w=this.chart.inverted;if(v){if(p(v)){var A=v[0]||{enabled:!1};var c=v[1]||{enabled:!1}}else A=k({},v),A.x=v.xHigh,A.y=v.yHigh,c=k({},v),c.x=v.xLow,c.y=v.yLow;if(A.enabled||this._hasPointLabels){for(f=n;f--;)if(q=a[f]){var d=A.inside?q.plotHigh<q.plotLow:q.plotHigh>q.plotLow;q.y=q.high;q._plotY=q.plotY;q.plotY=q.plotHigh;g[f]=q.dataLabel;
q.dataLabel=q.dataLabelUpper;q.below=d;w?A.align||(A.align=d?"right":"left"):A.verticalAlign||(A.verticalAlign=d?"top":"bottom")}this.options.dataLabels=A;b.drawDataLabels&&b.drawDataLabels.apply(this,arguments);for(f=n;f--;)if(q=a[f])q.dataLabelUpper=q.dataLabel,q.dataLabel=g[f],delete q.dataLabels,q.y=q.low,q.plotY=q._plotY}if(c.enabled||this._hasPointLabels){for(f=n;f--;)if(q=a[f])d=c.inside?q.plotHigh<q.plotLow:q.plotHigh>q.plotLow,q.below=!d,w?c.align||(c.align=d?"left":"right"):c.verticalAlign||
(c.verticalAlign=d?"bottom":"top");this.options.dataLabels=c;b.drawDataLabels&&b.drawDataLabels.apply(this,arguments)}if(A.enabled)for(f=n;f--;)if(q=a[f])q.dataLabels=[q.dataLabelUpper,q.dataLabel].filter(function(g){return!!g});this.options.dataLabels=v}};d.prototype.alignDataLabel=function(){x.alignDataLabel.apply(this,arguments)};d.prototype.drawPoints=function(){var a=this.points.length,c;b.drawPoints.apply(this,arguments);for(c=0;c<a;){var f=this.points[c];f.origProps={plotY:f.plotY,plotX:f.plotX,
isInside:f.isInside,negative:f.negative,zone:f.zone,y:f.y};f.lowerGraphic=f.graphic;f.graphic=f.upperGraphic;f.plotY=f.plotHigh;n(f.plotHighX)&&(f.plotX=f.plotHighX);f.y=y(f.high,f.origProps.y);f.negative=f.y<(this.options.threshold||0);this.zones.length&&(f.zone=f.getZone());this.chart.polar||(f.isInside=f.isTopInside="undefined"!==typeof f.plotY&&0<=f.plotY&&f.plotY<=this.yAxis.len&&0<=f.plotX&&f.plotX<=this.xAxis.len);c++}b.drawPoints.apply(this,arguments);for(c=0;c<a;)f=this.points[c],f.upperGraphic=
f.graphic,f.graphic=f.lowerGraphic,f.origProps&&(k(f,f.origProps),delete f.origProps),c++};d.defaultOptions=B(c.defaultOptions,{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}});return d}(c);k(a.prototype,{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,pointClass:e,setStackedPoints:h});
t.registerSeriesType("arearange",a);"";return a});z(e,"Series/AreaSplineRange/AreaSplineRangeSeries.js",[e["Series/AreaRange/AreaRangeSeries.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h){var d=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var k in a)a.hasOwnProperty(k)&&(b[k]=a[k])};return a(c,d)};return function(c,d){function b(){this.constructor=c}a(c,
d);c.prototype=null===d?Object.create(d):(b.prototype=d.prototype,new b)}}(),a=c.seriesTypes.spline,t=h.merge;h=h.extend;var m=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.data=void 0;c.points=void 0;return c}d(c,a);c.defaultOptions=t(e.defaultOptions);return c}(e);h(m.prototype,{getPointSpline:a.prototype.getPointSpline});c.registerSeriesType("areasplinerange",m);"";return m});z(e,"Series/BoxPlot/BoxPlotSeries.js",[e["Series/Column/ColumnSeries.js"],e["Core/Globals.js"],
e["Core/Color/Palette.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h,d,a){var t=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(b,c)};return function(b,c){function k(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}();c=c.noop;var m=a.extend,l=a.merge,r=a.pick;
a=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}t(b,a);b.prototype.pointAttribs=function(){return{}};b.prototype.translate=function(){var b=this.yAxis,c=this.pointArrayMap;a.prototype.translate.apply(this);this.points.forEach(function(a){c.forEach(function(c){null!==a[c]&&(a[c+"Plot"]=b.translate(a[c],0,1,0,1))});a.plotHigh=a.highPlot})};b.prototype.drawPoints=function(){var b=this,a=b.options,c=b.chart,d=c.renderer,
l,h,m,e,I,f,g=0,v,q,w,A,F=!1!==b.doQuartiles,t,x=b.options.whiskerLength;b.points.forEach(function(k){var p=k.graphic,n=p?"animate":"attr",y=k.shapeArgs,G={},u={},B={},K={},H=k.color||b.color;"undefined"!==typeof k.plotY&&(v=Math.round(y.width),q=Math.floor(y.x),w=q+v,A=Math.round(v/2),l=Math.floor(F?k.q1Plot:k.lowPlot),h=Math.floor(F?k.q3Plot:k.lowPlot),m=Math.floor(k.highPlot),e=Math.floor(k.lowPlot),p||(k.graphic=p=d.g("point").add(b.group),k.stem=d.path().addClass("highcharts-boxplot-stem").add(p),
x&&(k.whiskers=d.path().addClass("highcharts-boxplot-whisker").add(p)),F&&(k.box=d.path(void 0).addClass("highcharts-boxplot-box").add(p)),k.medianShape=d.path(void 0).addClass("highcharts-boxplot-median").add(p)),c.styledMode||(u.stroke=k.stemColor||a.stemColor||H,u["stroke-width"]=r(k.stemWidth,a.stemWidth,a.lineWidth),u.dashstyle=k.stemDashStyle||a.stemDashStyle||a.dashStyle,k.stem.attr(u),x&&(B.stroke=k.whiskerColor||a.whiskerColor||H,B["stroke-width"]=r(k.whiskerWidth,a.whiskerWidth,a.lineWidth),
B.dashstyle=k.whiskerDashStyle||a.whiskerDashStyle||a.dashStyle,k.whiskers.attr(B)),F&&(G.fill=k.fillColor||a.fillColor||H,G.stroke=a.lineColor||H,G["stroke-width"]=a.lineWidth||0,G.dashstyle=k.boxDashStyle||a.boxDashStyle||a.dashStyle,k.box.attr(G)),K.stroke=k.medianColor||a.medianColor||H,K["stroke-width"]=r(k.medianWidth,a.medianWidth,a.lineWidth),K.dashstyle=k.medianDashStyle||a.medianDashStyle||a.dashStyle,k.medianShape.attr(K)),f=k.stem.strokeWidth()%2/2,g=q+A+f,p=[["M",g,h],["L",g,m],["M",
g,l],["L",g,e]],k.stem[n]({d:p}),F&&(f=k.box.strokeWidth()%2/2,l=Math.floor(l)+f,h=Math.floor(h)+f,q+=f,w+=f,p=[["M",q,h],["L",q,l],["L",w,l],["L",w,h],["L",q,h],["Z"]],k.box[n]({d:p})),x&&(f=k.whiskers.strokeWidth()%2/2,m+=f,e+=f,t=/%$/.test(x)?A*parseFloat(x)/100:x/2,p=[["M",g-t,m],["L",g+t,m],["M",g-t,e],["L",g+t,e]],k.whiskers[n]({d:p})),I=Math.round(k.medianPlot),f=k.medianShape.strokeWidth()%2/2,I+=f,p=[["M",q,I],["L",w,I]],k.medianShape[n]({d:p}))})};b.prototype.toYData=function(b){return[b.low,
b.q1,b.median,b.q3,b.high]};b.defaultOptions=l(e.defaultOptions,{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},whiskerLength:"50%",fillColor:h.backgroundColor,lineWidth:1,medianWidth:2,whiskerWidth:2});return b}(e);m(a.prototype,{pointArrayMap:["low","q1","median","q3","high"],pointValKey:"high",
drawDataLabels:c,setStackedPoints:c});d.registerSeriesType("boxplot",a);"";return a});z(e,"Series/Bubble/BubbleLegendDefaults.js",[e["Core/Color/Palette.js"]],function(e){return{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:"10px",color:e.neutralColor100},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,
ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}});z(e,"Series/Bubble/BubbleLegendItem.js",[e["Core/Color/Color.js"],e["Core/FormatUtilities.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,c,h,d){var a=e.parse,t=h.noop,m=d.arrayMax,l=d.arrayMin,r=d.isNumber,x=d.merge,b=d.pick,n=d.stableSort;"";return function(){function k(b,a){this.options=this.symbols=this.visible=this.selected=this.ranges=this.movementX=
this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=t;this.init(b,a)}k.prototype.init=function(b,a){this.options=b;this.visible=!0;this.chart=a.chart;this.legend=a};k.prototype.addToLegend=function(b){b.splice(this.options.legendIndex,0,this)};k.prototype.drawLegendSymbol=function(a){var c=this.chart,k=this.options,d=b(a.options.itemDistance,20),p=k.ranges,l=k.connectorDistance;this.fontMetrics=
c.renderer.fontMetrics(k.labels.style.fontSize);p&&p.length&&r(p[0].value)?(n(p,function(b,f){return f.value-b.value}),this.ranges=p,this.setOptions(),this.render(),a=this.getMaxLabelSize(),p=this.ranges[0].radius,c=2*p,l=l-p+a.width,l=0<l?l:0,this.maxLabel=a,this.movementX="left"===k.labels.align?l:0,this.legendItemWidth=c+l+d,this.legendItemHeight=c+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};k.prototype.setOptions=function(){var c=this.ranges,k=this.options,d=this.chart.series[k.seriesIndex],
n=this.legend.baseline,l={zIndex:k.zIndex,"stroke-width":k.borderWidth},h={zIndex:k.zIndex,"stroke-width":k.connectorWidth},e={align:this.legend.options.rtl||"left"===k.labels.align?"right":"left",zIndex:k.zIndex},f=d.options.marker.fillOpacity,g=this.chart.styledMode;c.forEach(function(v,q){g||(l.stroke=b(v.borderColor,k.borderColor,d.color),l.fill=b(v.color,k.color,1!==f?a(d.color).setOpacity(f).get("rgba"):d.color),h.stroke=b(v.connectorColor,k.connectorColor,d.color));c[q].radius=this.getRangeRadius(v.value);
c[q]=x(c[q],{center:c[0].radius-c[q].radius+n});g||x(!0,c[q],{bubbleAttribs:x(l),connectorAttribs:x(h),labelAttribs:e})},this)};k.prototype.getRangeRadius=function(b){var a=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,a.ranges[a.ranges.length-1].value,a.ranges[0].value,a.minSize,a.maxSize,b)};k.prototype.render=function(){var b=this.chart.renderer,a=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=
b.g("bubble-legend");this.legendItem=b.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(b){b.value>=a&&this.renderRange(b)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};k.prototype.renderRange=function(b){var a=this.options,c=a.labels,k=this.chart,d=k.series[a.seriesIndex],n=k.renderer,p=this.symbols;k=p.labels;var f=b.center,g=Math.abs(b.radius),v=a.connectorDistance||
0,q=c.align,w=a.connectorWidth,A=this.ranges[0].radius||0,l=f-g-a.borderWidth/2+w/2,h=this.fontMetrics;h=h.f/2-(h.h-h.f)/2;var e=n.styledMode;v=this.legend.options.rtl||"left"===q?-v:v;"center"===q&&(v=0,a.connectorDistance=0,b.labelAttribs.align="center");q=l+a.labels.y;var m=A+v+a.labels.x;p.bubbleItems.push(n.circle(A,f+((l%1?1:.5)-(w%2?0:.5)),g).attr(e?{}:b.bubbleAttribs).addClass((e?"highcharts-color-"+d.colorIndex+" ":"")+"highcharts-bubble-legend-symbol "+(a.className||"")).add(this.legendSymbol));
p.connectors.push(n.path(n.crispLine([["M",A,l],["L",A+v,l]],a.connectorWidth)).attr(e?{}:b.connectorAttribs).addClass((e?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(a.connectorClassName||"")).add(this.legendSymbol));b=n.text(this.formatLabel(b),m,q+h).attr(e?{}:b.labelAttribs).css(e?{}:c.style).addClass("highcharts-bubble-legend-labels "+(a.labels.className||"")).add(this.legendSymbol);k.push(b);b.placed=!0;b.alignAttr={x:m,y:q+h}};k.prototype.getMaxLabelSize=
function(){var b,a;this.symbols.labels.forEach(function(c){a=c.getBBox(!0);b=b?a.width>b.width?a:b:a});return b||{}};k.prototype.formatLabel=function(b){var a=this.options,k=a.labels.formatter;a=a.labels.format;var d=this.chart.numberFormatter;return a?c.format(a,b):k?k.call(b):d(b.value,1)};k.prototype.hideOverlappingLabels=function(){var b=this.chart,a=this.symbols;!this.options.labels.allowOverlap&&a&&(b.hideOverlappingLabels(a.labels),a.labels.forEach(function(b,c){b.newOpacity?b.newOpacity!==
b.oldOpacity&&a.connectors[c].show():a.connectors[c].hide()}))};k.prototype.getRanges=function(){var a=this.legend.bubbleLegend,c=a.options.ranges,k,d=Number.MAX_VALUE,n=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(k=a.zData.filter(r),k.length&&(d=b(a.options.zMin,Math.min(d,Math.max(l(k),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),n=b(a.options.zMax,Math.max(n,m(k)))))});var h=d===n?[{value:n}]:[{value:d},{value:(d+n)/2},{value:n,
autoRanges:!0}];c.length&&c[0].radius&&h.reverse();h.forEach(function(b,a){c&&c[a]&&(h[a]=x(c[a],b))});return h};k.prototype.predictBubbleSizes=function(){var b=this.chart,a=this.fontMetrics,c=b.legend.options,k="horizontal"===c.layout,d=k?b.legend.lastLineHeight:0,n=b.plotSizeX,l=b.plotSizeY,f=b.series[this.options.seriesIndex];b=Math.ceil(f.minPxSize);var g=Math.ceil(f.maxPxSize),v=Math.min(l,n);f=f.options.maxSize;if(c.floating||!/%$/.test(f))a=g;else if(f=parseFloat(f),a=(v+d-a.h/2)*f/100/(f/
100+1),k&&l-a>=n||!k&&n-a>=l)a=g;return[b,Math.ceil(a)]};k.prototype.updateRanges=function(b,a){var c=this.legend.options.bubbleLegend;c.minSize=b;c.maxSize=a;c.ranges=this.getRanges()};k.prototype.correctSizes=function(){var b=this.legend,a=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(a.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,a.maxPxSize),b.render())};return k}()});z(e,"Series/Bubble/BubbleLegendComposition.js",[e["Series/Bubble/BubbleLegendDefaults.js"],
e["Series/Bubble/BubbleLegendItem.js"],e["Core/DefaultOptions.js"],e["Core/Utilities.js"]],function(e,c,h,d){var a=h.setOptions,t=d.addEvent,m=d.objectEach,l=d.wrap,r;(function(d){function b(b,a,c){var d=this.legend,f=0<=n(this);if(d&&d.options.enabled&&d.bubbleLegend&&d.options.bubbleLegend.autoRanges&&f){var g=d.bubbleLegend.options;f=d.bubbleLegend.predictBubbleSizes();d.bubbleLegend.updateRanges(f[0],f[1]);g.placed||(d.group.placed=!1,d.allItems.forEach(function(g){g.legendGroup.translateY=null}));
d.render();this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();g.placed||(b.setScale(),b.updateNames(),m(b.ticks,function(g){g.isNew=!0;g.isNewLabel=!0}))});g.placed=!0;this.getMargins();b.call(this,a,c);d.bubbleLegend.correctSizes();x(d,k(d))}else b.call(this,a,c),d&&d.options.enabled&&d.bubbleLegend&&(d.render(),x(d,k(d)))}function n(b){b=b.series;for(var a=0;a<b.length;){if(b[a]&&b[a].isBubble&&b[a].visible&&b[a].zData.length)return a;a++}return-1}function k(b){b=b.allItems;var a=
[],c=b.length,k,f=0;for(k=0;k<c;k++)if(b[k].legendItemHeight&&(b[k].itemHeight=b[k].legendItemHeight),b[k]===b[c-1]||b[k+1]&&b[k]._legendItemPos[1]!==b[k+1]._legendItemPos[1]){a.push({height:0});var g=a[a.length-1];for(f;f<=k;f++)b[f].itemHeight>g.height&&(g.height=b[f].itemHeight);g.step=k}return a}function h(b){var a=this.bubbleLegend,k=this.options,d=k.bubbleLegend,f=n(this.chart);a&&a.ranges&&a.ranges.length&&(d.ranges.length&&(d.autoRanges=!!d.ranges[0].autoRanges),this.destroyItem(a));0<=f&&
k.enabled&&d.enabled&&(d.seriesIndex=f,this.bubbleLegend=new c(d,this),this.bubbleLegend.addToLegend(b.allItems))}function r(){var b=this.chart,a=this.visible,c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,b=0<=n(b),c.bubbleLegend.visible!==b&&(c.update({bubbleLegend:{enabled:b}}),c.bubbleLegend.visible=b),this.visible=a)}function x(b,a){var c=b.options.rtl,k,f,g,v=0;b.allItems.forEach(function(b,w){k=b.legendGroup.translateX;f=b._legendItemPos[1];if((g=b.movementX)||
c&&b.ranges)g=c?k-b.options.maxSize/2:k+g,b.legendGroup.attr({translateX:g});w>a[v].step&&v++;b.legendGroup.attr({translateY:Math.round(f+a[v].height/2)});b._legendItemPos[1]=f+a[v].height/2})}d.compose=function(c,k,d){a({legend:{bubbleLegend:e}});t(k,"afterGetAllItems",h);t(d,"legendItemClick",r);l(c.prototype,"drawChartBox",b)}})(r||(r={}));return r});z(e,"Series/Bubble/BubblePoint.js",[e["Core/Series/Point.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h){var d=this&&
this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(c,d)};return function(c,d){function l(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(l.prototype=d.prototype,new l)}}();h=h.extend;c=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.series=void 0;return c}d(c,a);c.prototype.haloPath=function(a){return e.prototype.haloPath.call(this,
0===a?0:(this.marker?this.marker.radius||0:0)+a)};return c}(c.seriesTypes.scatter.prototype.pointClass);h(c.prototype,{ttBelow:!1});return c});z(e,"Series/Bubble/BubbleSeries.js",[e["Core/Axis/Axis.js"],e["Series/Bubble/BubbleLegendComposition.js"],e["Series/Bubble/BubblePoint.js"],e["Core/Color/Color.js"],e["Core/Globals.js"],e["Core/Series/Series.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h,d,a,t,m,l){var r=this&&this.__extends||function(){var b=function(g,a){b=
Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,g){b.__proto__=g}||function(b,g){for(var a in g)g.hasOwnProperty(a)&&(b[a]=g[a])};return b(g,a)};return function(g,a){function f(){this.constructor=g}b(g,a);g.prototype=null===a?Object.create(a):(f.prototype=a.prototype,new f)}}(),x=d.parse;d=a.noop;var b=m.seriesTypes;a=b.column;var n=b.scatter,k=l.arrayMax,p=l.arrayMin,y=l.clamp,B=l.extend,G=l.isNumber,D=l.merge,u=l.pick,I=l.pInt;l=function(b){function g(){var g=null!==b&&b.apply(this,
arguments)||this;g.data=void 0;g.maxPxSize=void 0;g.minPxSize=void 0;g.options=void 0;g.points=void 0;g.radii=void 0;g.yData=void 0;g.zData=void 0;return g}r(g,b);g.prototype.animate=function(b){!b&&this.points.length<this.options.animationLimit&&this.points.forEach(function(b){var g=b.graphic;g&&g.width&&(this.hasRendered||g.attr({x:b.plotX,y:b.plotY,width:1,height:1}),g.animate(this.markerAttribs(b),this.options.animation))},this)};g.prototype.getRadii=function(b,g,a){var f=this.zData,c=this.yData,
k=a.minPxSize,q=a.maxPxSize,d=[];var v=0;for(a=f.length;v<a;v++){var w=f[v];d.push(this.getRadius(b,g,k,q,w,c[v]))}this.radii=d};g.prototype.getRadius=function(b,g,a,f,c,k){var q=this.options,d="width"!==q.sizeBy,v=q.zThreshold,w=g-b,n=.5;if(null===k||null===c)return null;if(G(c)){q.sizeByAbsoluteValue&&(c=Math.abs(c-v),w=Math.max(g-v,Math.abs(b-v)),b=0);if(c<b)return a/2-1;0<w&&(n=(c-b)/w)}d&&0<=n&&(n=Math.sqrt(n));return Math.ceil(a+n*(f-a))/2};g.prototype.hasData=function(){return!!this.processedXData.length};
g.prototype.pointAttribs=function(b,g){var a=this.options.marker.fillOpacity;b=t.prototype.pointAttribs.call(this,b,g);1!==a&&(b.fill=x(b.fill).setOpacity(a).get("rgba"));return b};g.prototype.translate=function(){var g,a=this.data,f=this.radii;b.prototype.translate.call(this);for(g=a.length;g--;){var c=a[g];var k=f?f[g]:0;G(k)&&k>=this.minPxSize/2?(c.marker=B(c.marker,{radius:k,width:2*k,height:2*k}),c.dlBox={x:c.plotX-k,y:c.plotY-k,width:2*k,height:2*k}):c.shapeArgs=c.plotY=c.dlBox=void 0}};g.compose=
c.compose;g.defaultOptions=D(n.defaultOptions,{dataLabels:{formatter:function(){var b=this.series.chart.numberFormatter,g=this.point.z;return G(g)?b(g,-1):""},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});
return g}(n);B(l.prototype,{alignDataLabel:a.prototype.alignDataLabel,applyZones:d,bubblePadding:!0,buildKDTree:d,directTouch:!0,isBubble:!0,pointArrayMap:["y","z"],pointClass:h,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});e.prototype.beforePadding=function(){var b=this,g=this.len,a=this.chart,c=0,d=g,n=this.isXAxis,l=n?"xData":"yData",h=this.min,e={},m=Math.min(a.plotWidth,a.plotHeight),t=Number.MAX_VALUE,r=-Number.MAX_VALUE,x=this.max-
h,B=g/x,D=[];this.series.forEach(function(g){var f=g.options;!g.bubblePadding||!g.visible&&a.options.chart.ignoreHiddenSeries||(b.allowZoomOutside=!0,D.push(g),n&&(["minSize","maxSize"].forEach(function(b){var g=f[b],a=/%$/.test(g);g=I(g);e[b]=a?m*g/100:g}),g.minPxSize=e.minSize,g.maxPxSize=Math.max(e.maxSize,e.minSize),g=g.zData.filter(G),g.length&&(t=u(f.zMin,y(p(g),!1===f.displayNegative?f.zThreshold:-Number.MAX_VALUE,t)),r=u(f.zMax,Math.max(r,k(g))))))});D.forEach(function(g){var a=g[l],f=a.length;
n&&g.getRadii(t,r,g);if(0<x)for(;f--;)if(G(a[f])&&b.dataMin<=a[f]&&a[f]<=b.max){var k=g.radii?g.radii[f]:0;c=Math.min((a[f]-h)*B-k,c);d=Math.max((a[f]-h)*B+k,d)}});D.length&&0<x&&!this.logarithmic&&(d-=g,B*=(g+Math.max(0,c)-Math.min(d,g))/g,[["min","userMin",c],["max","userMax",d]].forEach(function(g){"undefined"===typeof u(b.options[g[0]],b[g[1]])&&(b[g[0]]+=g[2]/B)}))};m.registerSeriesType("bubble",l);"";"";return l});z(e,"Series/ColumnRange/ColumnRangePoint.js",[e["Core/Series/SeriesRegistry.js"],
e["Core/Utilities.js"]],function(e,c){var h=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(c,d)};return function(c,d){function h(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(h.prototype=d.prototype,new h)}}(),d=e.seriesTypes;e=d.column.prototype.pointClass;var a=c.extend,t=c.isNumber;c=function(a){function c(){var c=
null!==a&&a.apply(this,arguments)||this;c.series=void 0;c.options=void 0;c.barX=void 0;c.pointWidth=void 0;c.shapeType=void 0;return c}h(c,a);c.prototype.isValid=function(){return t(this.low)};return c}(d.arearange.prototype.pointClass);a(c.prototype,{setState:e.prototype.setState});return c});z(e,"Series/ColumnRange/ColumnRangeSeries.js",[e["Series/ColumnRange/ColumnRangePoint.js"],e["Core/Globals.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h,d){var a=this&&this.__extends||
function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return b(a,c)};return function(a,c){function k(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}();c=c.noop;var t=h.seriesTypes,m=t.arearange,l=t.column,r=l.prototype,x=m.prototype,b=d.clamp,n=d.merge,k=d.pick;d=d.extend;var p={pointRange:null,marker:null,states:{hover:{halo:!1}}};
t=function(c){function d(){var b=null!==c&&c.apply(this,arguments)||this;b.data=void 0;b.points=void 0;b.options=void 0;return b}a(d,c);d.prototype.setOptions=function(){n(!0,arguments[0],{stacking:void 0});return x.setOptions.apply(this,arguments)};d.prototype.translate=function(){var a=this,c=a.yAxis,d=a.xAxis,n=d.startAngleRad,f,g=a.chart,v=a.xAxis.isRadial,q=Math.max(g.chartWidth,g.chartHeight)+999,w;r.translate.apply(a);a.points.forEach(function(A){var h=A.shapeArgs||{},e=a.options.minPointLength;
A.plotHigh=w=b(c.translate(A.high,0,1,0,1),-q,q);A.plotLow=b(A.plotY,-q,q);var l=w;var p=k(A.rectPlotY,A.plotY)-w;Math.abs(p)<e?(e-=p,p+=e,l-=e/2):0>p&&(p*=-1,l-=p);v?(f=A.barX+n,A.shapeType="arc",A.shapeArgs=a.polarArc(l+p,l,f,f+A.pointWidth)):(h.height=p,h.y=l,e=h.x,e=void 0===e?0:e,h=h.width,h=void 0===h?0:h,A.tooltipPos=g.inverted?[c.len+c.pos-g.plotLeft-l-p/2,d.len+d.pos-g.plotTop-e-h/2,p]:[d.left-g.plotLeft+e+h/2,c.pos-g.plotTop+l+p/2,p])})};d.prototype.crispCol=function(){return r.crispCol.apply(this,
arguments)};d.prototype.drawPoints=function(){return r.drawPoints.apply(this,arguments)};d.prototype.drawTracker=function(){return r.drawTracker.apply(this,arguments)};d.prototype.getColumnMetrics=function(){return r.getColumnMetrics.apply(this,arguments)};d.prototype.pointAttribs=function(){return r.pointAttribs.apply(this,arguments)};d.prototype.adjustForMissingColumns=function(){return r.adjustForMissingColumns.apply(this,arguments)};d.prototype.animate=function(){return r.animate.apply(this,arguments)};
d.prototype.translate3dPoints=function(){return r.translate3dPoints.apply(this,arguments)};d.prototype.translate3dShapes=function(){return r.translate3dShapes.apply(this,arguments)};d.defaultOptions=n(l.defaultOptions,m.defaultOptions,p);return d}(m);d(t.prototype,{directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:c,getSymbol:c,polarArc:function(){return r.polarArc.apply(this,arguments)},pointClass:e});h.registerSeriesType("columnrange",t);"";return t});z(e,"Series/ColumnPyramid/ColumnPyramidSeries.js",
[e["Series/Column/ColumnSeries.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h){var d=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(c,b)};return function(c,b){function d(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}(),a=e.prototype,t=h.clamp,m=h.merge,
l=h.pick;h=function(c){function h(){var b=null!==c&&c.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}d(h,c);h.prototype.translate=function(){var b=this,c=b.chart,d=b.options,h=b.dense=2>b.closestPointRange*b.xAxis.transA;h=b.borderWidth=l(d.borderWidth,h?0:1);var e=b.yAxis,m=d.threshold,x=b.translatedThreshold=e.getThreshold(m),r=l(d.minPointLength,5),u=b.getColumnMetrics(),I=u.width,f=b.barW=Math.max(I,1+2*h),g=b.pointXOffset=u.offset;c.inverted&&(x-=.5);d.pointPadding&&
(f=Math.ceil(f));a.translate.apply(b);b.points.forEach(function(a){var k=l(a.yBottom,x),w=999+Math.abs(k),v=t(a.plotY,-w,e.len+w);w=a.plotX+g;var h=f/2,n=Math.min(v,k);k=Math.max(v,k)-n;var p;a.barX=w;a.pointWidth=I;a.tooltipPos=c.inverted?[e.len+e.pos-c.plotLeft-v,b.xAxis.len-w-h,k]:[w+h,v+e.pos-c.plotTop,k];v=m+(a.total||a.y);"percent"===d.stacking&&(v=m+(0>a.y)?-100:100);v=e.toPixels(v,!0);var y=(p=c.plotHeight-v-(c.plotHeight-x))?h*(n-v)/p:0;var u=p?h*(n+k-v)/p:0;p=w-y+h;y=w+y+h;var J=w+u+h;u=
w-u+h;var C=n-r;var B=n+k;0>a.y&&(C=n,B=n+k+r);c.inverted&&(J=c.plotWidth-n,p=v-(c.plotWidth-x),y=h*(v-J)/p,u=h*(v-(J-k))/p,p=w+h+y,y=p-2*y,J=w-u+h,u=w+u+h,C=n,B=n+k-r,0>a.y&&(B=n+k+r));a.shapeType="path";a.shapeArgs={x:p,y:C,width:y-p,height:k,d:[["M",p,C],["L",y,C],["L",J,B],["L",u,B],["Z"]]}})};h.defaultOptions=m(e.defaultOptions,{});return h}(e);c.registerSeriesType("columnpyramid",h);"";return h});z(e,"Series/ErrorBar/ErrorBarSeries.js",[e["Series/BoxPlot/BoxPlotSeries.js"],e["Series/Column/ColumnSeries.js"],
e["Core/Color/Palette.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h,d,a){var t=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),m=d.seriesTypes.arearange,l=a.merge;a=
a.extend;var r=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}t(b,a);b.prototype.getColumnMetrics=function(){return this.linkedParent&&this.linkedParent.columnMetrics||c.prototype.getColumnMetrics.call(this)};b.prototype.drawDataLabels=function(){var b=this.pointValKey;m&&(m.prototype.drawDataLabels.call(this),this.data.forEach(function(a){a.y=a[b]}))};b.prototype.toYData=function(b){return[b.low,b.high]};b.defaultOptions=
l(e.defaultOptions,{color:h.neutralColor100,grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},whiskerWidth:null});return b}(e);a(r.prototype,{pointArrayMap:["low","high"],pointValKey:"high",doQuartiles:!1});d.registerSeriesType("errorbar",r);"";return r});z(e,"Series/Gauge/GaugePoint.js",[e["Core/Series/SeriesRegistry.js"]],function(e){var c=this&&this.__extends||function(){var c=function(d,
a){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return c(d,a)};return function(d,a){function h(){this.constructor=d}c(d,a);d.prototype=null===a?Object.create(a):(h.prototype=a.prototype,new h)}}();return function(h){function d(){var a=null!==h&&h.apply(this,arguments)||this;a.options=void 0;a.series=void 0;a.shapeArgs=void 0;return a}c(d,h);d.prototype.setState=function(a){this.state=a};return d}(e.series.prototype.pointClass)});
z(e,"Series/Gauge/GaugeSeries.js",[e["Series/Gauge/GaugePoint.js"],e["Core/Globals.js"],e["Core/Color/Palette.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h,d,a){var t=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return b(a,c)};return function(a,c){function d(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):
(d.prototype=c.prototype,new d)}}();c=c.noop;var m=d.series,l=d.seriesTypes.column,r=a.clamp,x=a.isNumber,b=a.extend,n=a.merge,k=a.pick,p=a.pInt;a=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.points=void 0;a.options=void 0;a.yAxis=void 0;return a}t(a,b);a.prototype.translate=function(){var b=this.yAxis,a=this.options,c=b.center;this.generatePoints();this.points.forEach(function(d){var f=n(a.dial,d.dial),g=p(k(f.radius,"80%"))*c[2]/200,v=p(k(f.baseLength,"70%"))*
g/100,q=p(k(f.rearLength,"10%"))*g/100,w=f.baseWidth||3,h=f.topWidth||1,e=a.overshoot,l=b.startAngleRad+b.translate(d.y,null,null,null,!0);if(x(e)||!1===a.wrap)e=x(e)?e/180*Math.PI:0,l=r(l,b.startAngleRad-e,b.endAngleRad+e);l=180*l/Math.PI;d.shapeType="path";d.shapeArgs={d:f.path||[["M",-q,-w/2],["L",v,-w/2],["L",g,-h/2],["L",g,h/2],["L",v,w/2],["L",-q,w/2],["Z"]],translateX:c[0],translateY:c[1],rotation:l};d.plotX=c[0];d.plotY=c[1]})};a.prototype.drawPoints=function(){var b=this,a=b.chart,c=b.yAxis.center,
d=b.pivot,f=b.options,g=f.pivot,v=a.renderer;b.points.forEach(function(g){var c=g.graphic,d=g.shapeArgs,k=d.d,q=n(f.dial,g.dial);c?(c.animate(d),d.d=k):g.graphic=v[g.shapeType](d).attr({rotation:d.rotation,zIndex:1}).addClass("highcharts-dial").add(b.group);if(!a.styledMode)g.graphic[c?"animate":"attr"]({stroke:q.borderColor||"none","stroke-width":q.borderWidth||0,fill:q.backgroundColor||h.neutralColor100})});d?d.animate({translateX:c[0],translateY:c[1]}):(b.pivot=v.circle(0,0,k(g.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(c[0],
c[1]).add(b.group),a.styledMode||b.pivot.attr({"stroke-width":g.borderWidth||0,stroke:g.borderColor||h.neutralColor20,fill:g.backgroundColor||h.neutralColor100}))};a.prototype.animate=function(b){var a=this;b||a.points.forEach(function(b){var c=b.graphic;c&&(c.attr({rotation:180*a.yAxis.startAngleRad/Math.PI}),c.animate({rotation:b.shapeArgs.rotation},a.options.animation))})};a.prototype.render=function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,
this.chart.seriesGroup);m.prototype.render.call(this);this.group.clip(this.chart.clipRect)};a.prototype.setData=function(b,a){m.prototype.setData.call(this,b,!1);this.processData();this.generatePoints();k(a,!0)&&this.chart.redraw()};a.prototype.hasData=function(){return!!this.points.length};a.defaultOptions=n(m.defaultOptions,{dataLabels:{borderColor:h.neutralColor20,borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},
showInLegend:!1});return a}(m);b(a.prototype,{angular:!0,directTouch:!0,drawGraph:c,drawTracker:l.prototype.drawTracker,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,pointClass:e,trackerGroups:["group","dataLabelsGroup"]});d.registerSeriesType("gauge",a);"";return a});z(e,"Series/PackedBubble/PackedBubblePoint.js",[e["Core/Chart/Chart.js"],e["Core/Series/Point.js"],e["Core/Series/SeriesRegistry.js"]],function(e,c,h){var d=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,c){a.__proto__=c}||function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])};return a(c,d)};return function(c,d){function h(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(h.prototype=d.prototype,new h)}}();return function(a){function h(){var c=null!==a&&a.apply(this,arguments)||this;c.degree=NaN;c.mass=NaN;c.radius=NaN;c.options=void 0;c.series=void 0;c.value=null;return c}d(h,a);h.prototype.destroy=function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,
this.series.layout.nodes);return c.prototype.destroy.apply(this,arguments)};h.prototype.firePointEvent=function(){var a=this.series.options;if(this.isParentNode&&a.parentNode){var d=a.allowPointSelect;a.allowPointSelect=a.parentNode.allowPointSelect;c.prototype.firePointEvent.apply(this,arguments);a.allowPointSelect=d}else c.prototype.firePointEvent.apply(this,arguments)};h.prototype.select=function(){var a=this.series.chart;this.isParentNode?(a.getSelectedPoints=a.getSelectedParentNodes,c.prototype.select.apply(this,
arguments),a.getSelectedPoints=e.prototype.getSelectedPoints):c.prototype.select.apply(this,arguments)};return h}(h.seriesTypes.bubble.prototype.pointClass)});z(e,"Series/Networkgraph/DraggableNodes.js",[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,c,h){var d=h.addEvent;c.dragNodesMixin={onMouseDown:function(a,c){c=this.chart.pointer.normalize(c);a.fixedPosition={chartX:c.chartX,chartY:c.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,
c){if(a.fixedPosition&&a.inDragMode){var d=this.chart,h=d.pointer.normalize(c);c=a.fixedPosition.chartX-h.chartX;h=a.fixedPosition.chartY-h.chartY;var e=void 0,x=void 0,b=d.graphLayoutsLookup;if(5<Math.abs(c)||5<Math.abs(h))e=a.fixedPosition.plotX-c,x=a.fixedPosition.plotY-h,d.isInsidePlot(e,x)&&(a.plotX=e,a.plotY=x,a.hasDragged=!0,this.redrawHalo(a),b.forEach(function(b){b.restartSimulation()}))}},onMouseUp:function(a,c){a.fixedPosition&&(a.hasDragged&&(this.layout.enableSimulation?this.layout.start():
this.chart.redraw()),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};d(e,"load",function(){var a=this,c,h,e;a.container&&(c=d(a.container,"mousedown",function(c){var l=a.hoverPoint;l&&l.series&&l.series.hasDraggableNodes&&l.series.options.draggable&&(l.series.onMouseDown(l,c),h=d(a.container,"mousemove",function(b){return l&&l.series&&l.series.onMouseMove(l,
b)}),e=d(a.container.ownerDocument,"mouseup",function(b){h();e();return l&&l.series&&l.series.onMouseUp(l,b)}))}));d(a,"destroy",function(){c()})})});z(e,"Series/Networkgraph/Integrations.js",[e["Core/Globals.js"]],function(e){e.networkgraphIntegrations={verlet:{attractiveForceFunction:function(c,h){return(h-c)/c},repulsiveForceFunction:function(c,h){return(h-c)/c*(h>c?1:0)},barycenter:function(){var c=this.options.gravitationalConstant,h=this.barycenter.xFactor,d=this.barycenter.yFactor;h=(h-(this.box.left+
this.box.width)/2)*c;d=(d-(this.box.top+this.box.height)/2)*c;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=h/a.mass/a.degree,a.plotY-=d/a.mass/a.degree)})},repulsive:function(c,h,d){h=h*this.diffTemperature/c.mass/c.degree;c.fixedPosition||(c.plotX+=d.x*h,c.plotY+=d.y*h)},attractive:function(c,h,d){var a=c.getMass(),e=-d.x*h*this.diffTemperature;h=-d.y*h*this.diffTemperature;c.fromNode.fixedPosition||(c.fromNode.plotX-=e*a.fromNode/c.fromNode.degree,c.fromNode.plotY-=h*a.fromNode/c.fromNode.degree);
c.toNode.fixedPosition||(c.toNode.plotX+=e*a.toNode/c.toNode.degree,c.toNode.plotY+=h*a.toNode/c.toNode.degree)},integrate:function(c,h){var d=-c.options.friction,a=c.options.maxSpeed,e=(h.plotX+h.dispX-h.prevX)*d;d*=h.plotY+h.dispY-h.prevY;var m=Math.abs,l=m(e)/(e||1);m=m(d)/(d||1);e=l*Math.min(a,Math.abs(e));d=m*Math.min(a,Math.abs(d));h.prevX=h.plotX+h.dispX;h.prevY=h.plotY+h.dispY;h.plotX+=e;h.plotY+=d;h.temperature=c.vectorLength({x:e,y:d})},getK:function(c){return Math.pow(c.box.width*c.box.height/
c.nodes.length,.5)}},euler:{attractiveForceFunction:function(c,e){return c*c/e},repulsiveForceFunction:function(c,e){return e*e/c},barycenter:function(){var c=this.options.gravitationalConstant,e=this.barycenter.xFactor,d=this.barycenter.yFactor;this.nodes.forEach(function(a){if(!a.fixedPosition){var h=a.getDegree();h*=1+h/2;a.dispX+=(e-a.plotX)*c*h/a.degree;a.dispY+=(d-a.plotY)*c*h/a.degree}})},repulsive:function(c,e,d,a){c.dispX+=d.x/a*e/c.degree;c.dispY+=d.y/a*e/c.degree},attractive:function(c,
e,d,a){var h=c.getMass(),m=d.x/a*e;e*=d.y/a;c.fromNode.fixedPosition||(c.fromNode.dispX-=m*h.fromNode/c.fromNode.degree,c.fromNode.dispY-=e*h.fromNode/c.fromNode.degree);c.toNode.fixedPosition||(c.toNode.dispX+=m*h.toNode/c.toNode.degree,c.toNode.dispY+=e*h.toNode/c.toNode.degree)},integrate:function(c,e){e.dispX+=e.dispX*c.options.friction;e.dispY+=e.dispY*c.options.friction;var d=e.temperature=c.vectorLength({x:e.dispX,y:e.dispY});0!==d&&(e.plotX+=e.dispX/d*Math.min(Math.abs(e.dispX),c.temperature),
e.plotY+=e.dispY/d*Math.min(Math.abs(e.dispY),c.temperature))},getK:function(c){return Math.pow(c.box.width*c.box.height/c.nodes.length,.3)}}}});z(e,"Series/Networkgraph/QuadTree.js",[e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,c){c=c.extend;var h=e.QuadTreeNode=function(c){this.box=c;this.boxSize=Math.min(c.width,c.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};c(h.prototype,{insert:function(c,a){this.isInternal?this.nodes[this.getBoxPosition(c)].insert(c,a-1):(this.isEmpty=
!1,this.body?a?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,a-1),this.body=!0),this.nodes[this.getBoxPosition(c)].insert(c,a-1)):(a=new h({top:c.plotX,left:c.plotY,width:.1,height:.1}),a.body=c,a.isInternal=!1,this.nodes.push(a)):(this.isInternal=!1,this.body=c))},updateMassAndCenter:function(){var c=0,a=0,e=0;this.isInternal?(this.nodes.forEach(function(d){d.isEmpty||(c+=d.mass,a+=d.plotX*d.mass,e+=d.plotY*d.mass)}),a/=c,e/=c):
this.body&&(c=this.body.mass,a=this.body.plotX,e=this.body.plotY);this.mass=c;this.plotX=a;this.plotY=e},divideBox:function(){var c=this.box.width/2,a=this.box.height/2;this.nodes[0]=new h({left:this.box.left,top:this.box.top,width:c,height:a});this.nodes[1]=new h({left:this.box.left+c,top:this.box.top,width:c,height:a});this.nodes[2]=new h({left:this.box.left+c,top:this.box.top+a,width:c,height:a});this.nodes[3]=new h({left:this.box.left,top:this.box.top+a,width:c,height:a})},getBoxPosition:function(c){var a=
c.plotY<this.box.top+this.box.height/2;return c.plotX<this.box.left+this.box.width/2?a?0:3:a?1:2}});e=e.QuadTree=function(c,a,e,m){this.box={left:c,top:a,width:e,height:m};this.maxDepth=25;this.root=new h(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};c(e.prototype,{insertNodes:function(c){c.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(c,a,e){var d;c||(c=this.root);c===this.root&&a&&(d=a(c));!1!==d&&(c.nodes.forEach(function(c){if(c.isInternal){a&&
(d=a(c));if(!1===d)return;this.visitNodeRecursive(c,a,e)}else c.body&&a&&a(c.body);e&&e(c)},this),c===this.root&&e&&e(c))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(c){c.updateMassAndCenter()})}})});z(e,"Series/Networkgraph/Layouts.js",[e["Core/Chart/Chart.js"],e["Core/Animation/AnimationUtilities.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,c,h,d){var a=c.setAnimation;c=d.addEvent;var t=d.clamp,m=d.defined,l=d.extend,r=d.isFunction,x=d.pick;h.layouts=
{"reingold-fruchterman":function(){}};l(h.layouts["reingold-fruchterman"].prototype,{init:function(b){this.options=b;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=h.networkgraphIntegrations[b.integration];this.enableSimulation=b.enableSimulation;this.attractiveForce=x(b.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=x(b.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=
b.approximation},updateSimulation:function(b){this.enableSimulation=x(b,this.options.enableSimulation)},start:function(){var b=this.series,a=this.options;this.currentStep=0;this.forces=b[0]&&b[0].forces||[];this.chart=b[0]&&b[0].chart;this.initialRendering&&(this.initPositions(),b.forEach(function(b){b.finishedAnimating=!0;b.render()}));this.setK();this.resetSimulation(a);this.enableSimulation&&this.step()},step:function(){var b=this,a=this.series;b.currentStep++;"barnes-hut"===b.approximation&&(b.createQuadTree(),
b.quadTree.calculateMassAndCenter());b.forces.forEach(function(a){b[a+"Forces"](b.temperature)});b.applyLimits(b.temperature);b.temperature=b.coolDown(b.startTemperature,b.diffTemperature,b.currentStep);b.prevSystemTemperature=b.systemTemperature;b.systemTemperature=b.getSystemTemperature();b.enableSimulation&&(a.forEach(function(b){b.chart&&b.render()}),b.maxIterations--&&isFinite(b.temperature)&&!b.isStable()?(b.simulation&&h.win.cancelAnimationFrame(b.simulation),b.simulation=h.win.requestAnimationFrame(function(){b.step()})):
b.simulation=!1)},stop:function(){this.simulation&&h.win.cancelAnimationFrame(this.simulation)},setArea:function(b,a,c,d){this.box={left:b,top:a,width:c,height:d}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(b,a){b.forEach(function(b){-1===a.indexOf(b)&&a.push(b)})},removeElementFromCollection:function(b,a){b=a.indexOf(b);-1!==b&&a.splice(b,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},
resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},restartSimulation:function(){this.simulation?this.resetSimulation():(this.setInitialRendering(!1),this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))},setMaxIterations:function(b){this.maxIterations=x(b,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=
Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(b){this.initialRendering=b},createQuadTree:function(){this.quadTree=new h.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var b=this.options.initialPositions;r(b)?(b.call(this),this.nodes.forEach(function(b){m(b.prevX)||(b.prevX=b.plotX);m(b.prevY)||(b.prevY=
b.plotY);b.dispX=0;b.dispY=0})):"circle"===b?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function b(a){a.linksFrom.forEach(function(a){l[a.toNode.id]||(l[a.toNode.id]=!0,h.push(a.toNode),b(a.toNode))})}var a=this.box,c=this.nodes,d=2*Math.PI/(c.length+1),e=c.filter(function(b){return 0===b.linksTo.length}),h=[],l={},m=this.options.initialPositionRadius;e.forEach(function(a){h.push(a);b(a)});h.length?c.forEach(function(b){-1===h.indexOf(b)&&h.push(b)}):h=
c;h.forEach(function(b,c){b.plotX=b.prevX=x(b.plotX,a.width/2+m*Math.cos(c*d));b.plotY=b.prevY=x(b.plotY,a.height/2+m*Math.sin(c*d));b.dispX=0;b.dispY=0})},setRandomPositions:function(){function b(b){b=b*b/Math.PI;return b-=Math.floor(b)}var a=this.box,c=this.nodes,d=c.length+1;c.forEach(function(c,e){c.plotX=c.prevX=x(c.plotX,a.width*b(e));c.plotY=c.prevY=x(c.plotY,a.height*b(d+e));c.dispX=0;c.dispY=0})},force:function(b){this.integration[b].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();
this.force("barycenter")},getBarycenter:function(){var b=0,a=0,c=0;this.nodes.forEach(function(d){a+=d.plotX*d.mass;c+=d.plotY*d.mass;b+=d.mass});return this.barycenter={x:a,y:c,xFactor:a/b,yFactor:c/b}},barnesHutApproximation:function(b,a){var c=this.getDistXY(b,a),d=this.vectorLength(c);if(b!==a&&0!==d)if(a.isInternal)if(a.boxSize/d<this.options.theta&&0!==d){var e=this.repulsiveForce(d,this.k);this.force("repulsive",b,e*a.mass,c,d);var h=!1}else h=!0;else e=this.repulsiveForce(d,this.k),this.force("repulsive",
b,e*a.mass,c,d);return h},repulsiveForces:function(){var b=this;"barnes-hut"===b.approximation?b.nodes.forEach(function(a){b.quadTree.visitNodeRecursive(null,function(c){return b.barnesHutApproximation(a,c)})}):b.nodes.forEach(function(a){b.nodes.forEach(function(c){if(a!==c&&!a.fixedPosition){var d=b.getDistXY(a,c);var e=b.vectorLength(d);if(0!==e){var k=b.repulsiveForce(e,b.k);b.force("repulsive",a,k*c.mass,d,e)}}})})},attractiveForces:function(){var b=this,a,c,d;b.links.forEach(function(e){e.fromNode&&
e.toNode&&(a=b.getDistXY(e.fromNode,e.toNode),c=b.vectorLength(a),0!==c&&(d=b.attractiveForce(c,b.k),b.force("attractive",e,d,a,c)))})},applyLimits:function(){var b=this;b.nodes.forEach(function(a){a.fixedPosition||(b.integration.integrate(b,a),b.applyLimitBox(a,b.box),a.dispX=0,a.dispY=0)})},applyLimitBox:function(b,a){var c=b.radius;b.plotX=t(b.plotX,a.left+c,a.width-c);b.plotY=t(b.plotY,a.top+c,a.height-c)},coolDown:function(a,c,d){return a-c*d},isStable:function(){return.00001>Math.abs(this.systemTemperature-
this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,c){return a+c.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,c){a=this.getDistXY(a,c);return this.vectorLength(a)},getDistXY:function(a,c){var b=a.plotX-c.plotX;a=a.plotY-c.plotY;return{x:b,y:a,absX:Math.abs(b),absY:Math.abs(a)}}});c(e,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});
c(e,"render",function(){function b(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),d=!1,c=!0)}var c=!1;if(this.graphLayoutsLookup){a(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!d;){var d=!0;this.graphLayoutsLookup.forEach(b)}c&&this.series.forEach(function(a){a&&a.layout&&a.render()})}});c(e,"beforePrint",function(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)}),
this.redraw())});c(e,"afterPrint",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});this.redraw()})});z(e,"Series/PackedBubble/PackedBubbleComposition.js",[e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Core/Utilities.js"]],function(e,c,h){var d=c.layouts["reingold-fruchterman"],a=h.addEvent,t=h.extendClass,m=h.pick;e.prototype.getSelectedParentNodes=function(){var a=[];this.series.forEach(function(c){c.parentNode&&c.parentNode.selected&&a.push(c.parentNode)});
return a};c.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,c,d,b){return Math.min(a,(d.marker.radius+b.marker.radius)/2)},barycenter:function(){var a=this,c=a.options.gravitationalConstant,d=a.box,b=a.nodes,e,k;b.forEach(function(h){a.options.splitSeries&&!h.isParentNode?(e=h.series.parentNode.plotX,k=h.series.parentNode.plotY):(e=d.width/2,k=d.height/2);h.fixedPosition||(h.plotX-=(h.plotX-e)*c/(h.mass*Math.sqrt(b.length)),h.plotY-=(h.plotY-k)*c/(h.mass*Math.sqrt(b.length)))})},
repulsive:function(a,c,d,b){var e=c*this.diffTemperature/a.mass/a.degree;c=d.x*e;d=d.y*e;a.fixedPosition||(a.plotX+=c,a.plotY+=d);b.fixedPosition||(b.plotX-=c,b.plotY-=d)},integrate:c.networkgraphIntegrations.verlet.integrate,getK:c.noop};c.layouts.packedbubble=t(d,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},isStable:function(){var a=Math.abs(this.prevSystemTemperature-this.systemTemperature);return 1>Math.abs(10*this.systemTemperature/
Math.sqrt(this.nodes.length))&&.00001>a||0>=this.temperature},setCircularPositions:function(){var a=this,c=a.box,d=a.nodes,b=2*Math.PI/(d.length+1),e,k,h=a.options.initialPositionRadius;d.forEach(function(d,l){a.options.splitSeries&&!d.isParentNode?(e=d.series.parentNode.plotX,k=d.series.parentNode.plotY):(e=c.width/2,k=c.height/2);d.plotX=d.prevX=m(d.plotX,e+h*Math.cos(d.index||l*b));d.plotY=d.prevY=m(d.plotY,k+h*Math.sin(d.index||l*b));d.dispX=0;d.dispY=0})},repulsiveForces:function(){var a=this,
c,d,b,e=a.options.bubblePadding;a.nodes.forEach(function(k){k.degree=k.mass;k.neighbours=0;a.nodes.forEach(function(h){c=0;k===h||k.fixedPosition||!a.options.seriesInteraction&&k.series!==h.series||(b=a.getDistXY(k,h),d=a.vectorLength(b)-(k.marker.radius+h.marker.radius+e),0>d&&(k.degree+=.01,k.neighbours++,c=a.repulsiveForce(-d/Math.sqrt(k.neighbours),a.k,k,h)),a.force("repulsive",k,c*h.mass,b,h,d))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var c=
this.getDistXY(a,a.series.parentNode);var e=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(c);0>e&&e>-2*a.marker.radius&&(a.plotX-=.01*c.x,a.plotY-=.01*c.y)}d.prototype.applyLimitBox.apply(this,arguments)}});a(e,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints})});z(e,"Series/PackedBubble/PackedBubbleSeries.js",[e["Core/Color/Color.js"],e["Core/Globals.js"],e["Series/PackedBubble/PackedBubblePoint.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],
function(e,c,h,d,a){var t=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function g(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(g.prototype=c.prototype,new g)}}(),m=e.parse,l=d.series,r=d.seriesTypes.bubble,x=a.addEvent,b=a.clamp,n=a.defined,k=a.extend,p=a.fireEvent,y=a.isArray,B=a.isNumber,
z=a.merge,D=a.pick,u=c.dragNodesMixin;e=function(a){function f(){var b=null!==a&&a.apply(this,arguments)||this;b.chart=void 0;b.data=void 0;b.layout=void 0;b.options=void 0;b.points=void 0;b.xData=void 0;return b}t(f,a);f.prototype.accumulateAllPoints=function(a){var b=a.chart,c=[],g,f;for(g=0;g<b.series.length;g++)if(a=b.series[g],a.is("packedbubble")&&a.visible||!b.options.chart.ignoreHiddenSeries)for(f=0;f<a.yData.length;f++)c.push([null,null,a.yData[f],a.index,f,{id:f,marker:{radius:0}}]);return c};
f.prototype.addLayout=function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,f=this.chart.graphLayoutsLookup,d=this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=f=[]);var e=b[a.type];e||(a.enableSimulation=n(d.forExport)?!d.forExport:a.enableSimulation,b[a.type]=e=new c.layouts[a.type],e.init(a),f.splice(e.index,0,e));this.layout=e;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=1});e.setArea(0,0,this.chart.plotWidth,
this.chart.plotHeight);e.addElementsToCollection([this],e.series);e.addElementsToCollection(this.points,e.nodes)};f.prototype.addSeriesLayout=function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,f=this.chart.graphLayoutsLookup,d=z(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var e=b[a.type+"-series"];e||(b[a.type+"-series"]=e=new c.layouts[a.type],e.init(d),f.splice(e.index,0,e));this.parentNodeLayout=e;this.createParentNodes()};f.prototype.calculateParentRadius=
function(){var a=this.seriesBox();this.parentNodeRadius=b(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)};f.prototype.calculateZExtremes=function(){var a=this.options.zMin,b=this.options.zMax,c=Infinity,f=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){n(a)&&
(a>f&&(f=a),a<c&&(c=a))})});a=D(a,c);b=D(b,f);return[a,b]};f.prototype.checkOverlap=function(a,b){var c=a[0]-b[0],g=a[1]-b[1];return-.001>Math.sqrt(c*c+g*g)-Math.abs(a[2]+b[2])};f.prototype.createParentNodes=function(){var a=this,b=a.chart,c=a.parentNodeLayout,f,d=a.parentNode,e=a.pointClass;a.parentNodeMass=0;a.points.forEach(function(b){a.parentNodeMass+=Math.PI*Math.pow(b.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(b){b.seriesIndex===a.index&&(f=!0)});c.setArea(0,0,b.plotWidth,
b.plotHeight);f||(d||(d=(new e).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(d.plotX=a.parentNode.plotX,d.plotY=a.parentNode.plotY),a.parentNode=d,c.addElementsToCollection([a],c.series),c.addElementsToCollection([d],c.nodes))};f.prototype.deferLayout=function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())};
f.prototype.destroy=function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&this.parentNodeLayout&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));l.prototype.destroy.apply(this,arguments)};f.prototype.drawDataLabels=function(){var a=this.options.dataLabels.textPath,
b=this.points;l.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,l.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)};f.prototype.drawGraph=function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart;var b=this.layout.options.parentNodeOptions.marker;var c={fill:b.fillColor||
m(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||this.color,"stroke-width":b.lineWidth};this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",this.visible?"inherit":"hidden",.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();b=z({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},c);this.parentNode.graphic||
(this.graph=this.parentNode.graphic=a.renderer.symbol(c.symbol).add(this.parentNodesGroup));this.parentNode.graphic.attr(b)}};f.prototype.drawTracker=function(){var b=this.parentNode;a.prototype.drawTracker.call(this);if(b){var c=y(b.dataLabels)?b.dataLabels:b.dataLabel?[b.dataLabel]:[];b.graphic&&(b.graphic.element.point=b);c.forEach(function(a){a.div?a.div.point=b:a.element.point=b})}};f.prototype.getPointRadius=function(){var a=this,c=a.chart,f=a.options,d=f.useSimulation,e=Math.min(c.plotWidth,
c.plotHeight),k={},h=[],l=c.allDataPoints,n,p,m,r;["minSize","maxSize"].forEach(function(a){var b=parseInt(f[a],10),c=/%$/.test(f[a]);k[a]=c?e*b/100:b*Math.sqrt(l.length)});c.minRadius=n=k.minSize/Math.sqrt(l.length);c.maxRadius=p=k.maxSize/Math.sqrt(l.length);var x=d?a.calculateZExtremes():[n,p];(l||[]).forEach(function(c,g){m=d?b(c[2],x[0],x[1]):c[2];r=a.getRadius(x[0],x[1],n,p,m);0===r&&(r=null);l[g][2]=r;h.push(r)});a.radii=h};f.prototype.init=function(){l.prototype.init.apply(this,arguments);
this.eventsToUnbind.push(x(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)}));return this};f.prototype.onMouseUp=function(a){if(a.fixedPosition&&!a.removed){var b,c,g=this.layout,f=this.parentNodeLayout;f&&g.options.dragBetweenSeries&&f.nodes.forEach(function(f){a&&a.marker&&f!==a.series.parentNode&&(b=g.getDistXY(a,f),c=g.vectorLength(b)-f.marker.radius-a.marker.radius,0>c&&(f.series.addPoint(z(a.options,{plotX:a.plotX,plotY:a.plotY}),
!1),g.removeElementFromCollection(a,g.nodes),a.remove()))});u.onMouseUp.apply(this,arguments)}};f.prototype.placeBubbles=function(a){var b=this.checkOverlap,c=this.positionBubble,g=[],f=1,d=0,e=0;var k=[];var h;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){g.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(g.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),h=2;h<a.length;h++)a[h][2]=a[h][2]||1,k=c(g[f][d],g[f-1][e],a[h]),b(k,g[f][0])?(g.push([]),e=0,g[f+1].push(c(g[f][d],g[f][0],
a[h])),f++,d=0):1<f&&g[f-1][e+1]&&b(k,g[f-1][e+1])?(e++,g[f].push(c(g[f][d],g[f-1][e],a[h])),d++):(d++,g[f].push(k));this.chart.stages=g;this.chart.rawPositions=[].concat.apply([],g);this.resizeRadius();k=this.chart.rawPositions}return k};f.prototype.positionBubble=function(a,b,c){var g=Math.sqrt,f=Math.asin,d=Math.acos,e=Math.pow,k=Math.abs;g=g(e(a[0]-b[0],2)+e(a[1]-b[1],2));d=d((e(g,2)+e(c[2]+b[2],2)-e(c[2]+a[2],2))/(2*(c[2]+b[2])*g));f=f(k(a[0]-b[0])/g);a=(0>a[1]-b[1]?0:Math.PI)+d+f*(0>(a[0]-b[0])*
(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]};f.prototype.render=function(){var a=[];l.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(b){y(b.dataLabels)&&b.dataLabels.forEach(function(b){a.push(b)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))};f.prototype.resizeRadius=function(){var a=this.chart,b=a.rawPositions,c=Math.min,f=Math.max,d=a.plotLeft,e=a.plotTop,k=a.plotHeight,
h=a.plotWidth,l,n,p;var m=l=Number.POSITIVE_INFINITY;var r=n=Number.NEGATIVE_INFINITY;for(p=0;p<b.length;p++){var x=b[p][2];m=c(m,b[p][0]-x);r=f(r,b[p][0]+x);l=c(l,b[p][1]-x);n=f(n,b[p][1]+x)}p=[r-m,n-l];c=c.apply([],[(h-d)/p[0],(k-e)/p[1]]);if(1e-10<Math.abs(c-1)){for(p=0;p<b.length;p++)b[p][2]*=c;this.placeBubbles(b)}else a.diffY=k/2+e-l-(n-l)/2,a.diffX=h/2+d-m-(r-m)/2};f.prototype.seriesBox=function(){var a=this.chart,b=Math.max,c=Math.min,f,d=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+
a.plotHeight];this.data.forEach(function(a){n(a.plotX)&&n(a.plotY)&&a.marker.radius&&(f=a.marker.radius,d[0]=c(d[0],a.plotX-f),d[1]=b(d[1],a.plotX+f),d[2]=c(d[2],a.plotY-f),d[3]=b(d[3],a.plotY+f))});return B(d.width/d.height)?d:null};f.prototype.setVisible=function(){var a=this;l.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,
a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(b){a.layout.removeElementFromCollection(b,a.layout.nodes)}))};f.prototype.translate=function(){var a=this.chart,b=this.data,c=this.index,f,d=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();n(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());if(d)var e=
a.allDataPoints;else e=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(f=0;f<e.length;f++)if(e[f][3]===c){var h=b[e[f][4]];var l=D(e[f][2],void 0);d||(h.plotX=e[f][0]-a.plotLeft+a.diffX,h.plotY=e[f][1]-a.plotTop+a.diffY);B(l)&&(h.marker=k(h.marker,{radius:l,width:2*l,height:2*l}),h.radius=l)}d&&this.deferLayout();p(this,"afterTranslate")};f.defaultOptions=z(r.defaultOptions,{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",crisp:!1,tooltip:{pointFormat:"Value: {point.value}"},
draggable:!0,useSimulation:!0,parentNode:{allowPointSelect:!1},dataLabels:{formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.value;return B(b)?a(b,-1):""},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0,style:{transition:"opacity 2000ms"}},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,
maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}});return f}(r);k(e.prototype,{alignDataLabel:l.prototype.alignDataLabel,axisTypes:[],directTouch:!0,forces:["barycenter","repulsive"],hasDraggableNodes:!0,isCartesian:!1,noSharedTooltip:!0,onMouseDown:u.onMouseDown,
onMouseMove:u.onMouseMove,pointArrayMap:["value"],pointClass:h,pointValKey:"value",redrawHalo:u.redrawHalo,requireSorting:!1,searchPoint:c.noop,trackerGroups:["group","dataLabelsGroup","parentNodesGroup"]});d.registerSeriesType("packedbubble",e);"";"";return e});z(e,"Series/Polygon/PolygonSeries.js",[e["Core/Globals.js"],e["Core/Legend/LegendSymbol.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,h,d){var a=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}();e=e.noop;var t=h.series,m=h.seriesTypes,l=m.area,r=m.line,x=m.scatter;m=d.extend;var b=d.merge;d=function(c){function d(){var a=null!==c&&c.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}a(d,
c);d.prototype.getGraphPath=function(){for(var a=r.prototype.getGraphPath.call(this),b=a.length+1;b--;)(b===a.length||"M"===a[b][0])&&0<b&&a.splice(b,0,["Z"]);return this.areaPath=a};d.prototype.drawGraph=function(){this.options.fillColor=this.color;l.prototype.drawGraph.call(this)};d.defaultOptions=b(x.defaultOptions,{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0});return d}(x);m(d.prototype,{type:"polygon",drawLegendSymbol:c.drawRectangle,
drawTracker:t.prototype.drawTracker,setStackedPoints:e});h.registerSeriesType("polygon",d);"";return d});z(e,"Core/Axis/WaterfallAxis.js",[e["Extensions/Stacking.js"],e["Core/Utilities.js"]],function(e,c){var h=c.addEvent,d=c.objectEach,a;(function(a){function c(){var a=this.waterfall.stacks;a&&(a.changed=!1,delete a.alreadyChanged)}function l(){var a=this.options.stackLabels;a&&a.enabled&&this.waterfall.stacks&&this.waterfall.renderStackTotals()}function r(){for(var a=this.axes,b=this.series,c=b.length;c--;)b[c].options.stacking&&
(a.forEach(function(a){a.isXAxis||(a.waterfall.stacks.changed=!0)}),c=0)}function x(){this.waterfall||(this.waterfall=new b(this))}var b=function(){function a(a){this.axis=a;this.stacks={changed:!1}}a.prototype.renderStackTotals=function(){var a=this.axis,b=a.waterfall.stacks,c=a.stacking&&a.stacking.stackTotalGroup,h=new e(a,a.options.stackLabels,!1,0,void 0);this.dummyStackItem=h;d(b,function(a){d(a,function(a){h.total=a.stackTotal;a.label&&(h.label=a.label);e.prototype.render.call(h,c);a.label=
h.label;delete h.label})});h.total=null};return a}();a.Composition=b;a.compose=function(a,b){h(a,"init",x);h(a,"afterBuildStacks",c);h(a,"afterRender",l);h(b,"beforeRedraw",r)}})(a||(a={}));return a});z(e,"Series/Waterfall/WaterfallPoint.js",[e["Series/Column/ColumnSeries.js"],e["Core/Series/Point.js"],e["Core/Utilities.js"]],function(e,c,h){var d=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,
c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,d)};return function(c,d){function e(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}(),a=h.isNumber;return function(e){function h(){var a=null!==e&&e.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}d(h,e);h.prototype.getClassName=function(){var a=c.prototype.getClassName.call(this);this.isSum?a+=" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");
return a};h.prototype.isValid=function(){return a(this.y)||this.isSum||!!this.isIntermediateSum};return h}(e.prototype.pointClass)});z(e,"Series/Waterfall/WaterfallSeries.js",[e["Core/Axis/Axis.js"],e["Core/Chart/Chart.js"],e["Core/Color/Palette.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"],e["Core/Axis/WaterfallAxis.js"],e["Series/Waterfall/WaterfallPoint.js"]],function(e,c,h,d,a,t,m){var l=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function g(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(g.prototype=c.prototype,new g)}}(),r=d.seriesTypes,x=r.column,b=r.line,n=a.arrayMax,k=a.arrayMin,p=a.correctFloat;r=a.extend;var y=a.isNumber,z=a.merge,D=a.objectEach,H=a.pick;a=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.chart=void 0;b.data=void 0;b.options=
void 0;b.points=void 0;b.stackedYNeg=void 0;b.stackedYPos=void 0;b.stackKey=void 0;b.xData=void 0;b.yAxis=void 0;b.yData=void 0;return b}l(c,a);c.prototype.generatePoints=function(){var a;x.prototype.generatePoints.apply(this);var b=0;for(a=this.points.length;b<a;b++){var c=this.points[b];var d=this.processedYData[b];if(c.isIntermediateSum||c.isSum)c.y=p(d)}};c.prototype.translate=function(){var a=this.options,b=this.yAxis,c=H(a.minPointLength,5),d=c/2,e=a.threshold||0,h=e,k=e;a=a.stacking;var l=
b.waterfall.stacks[this.stackKey];x.prototype.translate.apply(this);for(var p=this.points,n=0;n<p.length;n++){var m=p[n];var r=this.processedYData[n];var C=m.shapeArgs;if(C&&y(r)){var t=[0,r];var u=m.y;if(a){if(l){t=l[n];if("overlap"===a){var z=t.stackState[t.stateIndex--];z=0<=u?z:z-u;Object.hasOwnProperty.call(t,"absolutePos")&&delete t.absolutePos;Object.hasOwnProperty.call(t,"absoluteNeg")&&delete t.absoluteNeg}else 0<=u?(z=t.threshold+t.posTotal,t.posTotal-=u):(z=t.threshold+t.negTotal,t.negTotal-=
u,z-=u),!t.posTotal&&Object.hasOwnProperty.call(t,"absolutePos")&&(t.posTotal=t.absolutePos,delete t.absolutePos),!t.negTotal&&Object.hasOwnProperty.call(t,"absoluteNeg")&&(t.negTotal=t.absoluteNeg,delete t.absoluteNeg);m.isSum||(t.connectorThreshold=t.threshold+t.stackTotal);b.reversed?(r=0<=u?z-u:z+u,u=z):(r=z,u=z-u);m.below=r<=e;C.y=b.translate(r,!1,!0,!1,!0)||0;C.height=Math.abs(C.y-(b.translate(u,!1,!0,!1,!0)||0));if(u=b.waterfall.dummyStackItem)u.x=n,u.label=l[n].label,u.setOffset(this.pointXOffset||
0,this.barW||0,this.stackedYNeg[n],this.stackedYPos[n])}}else z=Math.max(h,h+u)+t[0],C.y=b.translate(z,!1,!0,!1,!0)||0,m.isSum?(C.y=b.translate(t[1],!1,!0,!1,!0)||0,C.height=Math.min(b.translate(t[0],!1,!0,!1,!0)||0,b.len)-C.y,m.below=t[1]<=e):m.isIntermediateSum?(0<=u?(r=t[1]+k,u=k):(r=k,u=t[1]+k),b.reversed&&(r^=u,u^=r,r^=u),C.y=b.translate(r,!1,!0,!1,!0)||0,C.height=Math.abs(C.y-Math.min(b.translate(u,!1,!0,!1,!0)||0,b.len)),k+=t[1],m.below=r<=e):(C.height=0<r?(b.translate(h,!1,!0,!1,!0)||0)-C.y:
(b.translate(h,!1,!0,!1,!0)||0)-(b.translate(h-r,!1,!0,!1,!0)||0),h+=r,m.below=h<e),0>C.height&&(C.y+=C.height,C.height*=-1);m.plotY=C.y=Math.round(C.y||0)-this.borderWidth%2/2;C.height=Math.max(Math.round(C.height||0),.001);m.yBottom=C.y+C.height;C.height<=c&&!m.isNull?(C.height=c,C.y-=d,m.plotY=C.y,m.minPointLengthOffset=0>m.y?-d:d):(m.isNull&&(C.width=0),m.minPointLengthOffset=0);u=m.plotY+(m.negative?C.height:0);m.below&&(m.plotY+=C.height);m.tooltipPos&&(this.chart.inverted?m.tooltipPos[0]=b.len-
u:m.tooltipPos[1]=u)}}};c.prototype.processData=function(b){var c=this.options,d=this.yData,f=c.data,e=d.length,h=c.threshold||0,k,l,m,n,r;for(r=l=k=m=n=0;r<e;r++){var t=d[r];var u=f&&f[r]?f[r]:{};"sum"===t||u.isSum?d[r]=p(l):"intermediateSum"===t||u.isIntermediateSum?(d[r]=p(k),k=0):(l+=t,k+=t);m=Math.min(l,m);n=Math.max(l,n)}a.prototype.processData.call(this,b);c.stacking||(this.dataMin=m+h,this.dataMax=n)};c.prototype.toYData=function(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":
a.y};c.prototype.updateParallelArrays=function(b,c){a.prototype.updateParallelArrays.call(this,b,c);if("sum"===this.yData[0]||"intermediateSum"===this.yData[0])this.yData[0]=null};c.prototype.pointAttribs=function(a,b){var c=this.options.upColor;c&&!a.options.color&&(a.color=0<a.y?c:null);a=x.prototype.pointAttribs.call(this,a,b);delete a.dashstyle;return a};c.prototype.getGraphPath=function(){return[["M",0,0]]};c.prototype.getCrispPath=function(){var a=this.data,b=this.yAxis,c=a.length,d=Math.round(this.graph.strokeWidth())%
2/2,e=Math.round(this.borderWidth)%2/2,h=this.xAxis.reversed,k=this.yAxis.reversed,l=this.options.stacking,m=[],n;for(n=1;n<c;n++){var p=a[n].shapeArgs;var r=a[n-1];var t=a[n-1].shapeArgs;var u=b.waterfall.stacks[this.stackKey];var x=0<r.y?-t.height:0;u&&t&&p&&(u=u[n-1],l?(u=u.connectorThreshold,x=Math.round(b.translate(u,0,1,0,1)+(k?x:0))-d):x=t.y+r.minPointLengthOffset+e-d,m.push(["M",(t.x||0)+(h?0:t.width||0),x],["L",(p.x||0)+(h?p.width||0:0),x]));t&&m.length&&(!l&&0>r.y&&!k||0<r.y&&k)&&((r=m[m.length-
2])&&"number"===typeof r[2]&&(r[2]+=t.height||0),(r=m[m.length-1])&&"number"===typeof r[2]&&(r[2]+=t.height||0))}return m};c.prototype.drawGraph=function(){b.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})};c.prototype.setStackedPoints=function(){function a(a,b,c,d){if(G)for(c;c<G;c++)y.stackState[c]+=d;else y.stackState[0]=a,G=y.stackState.length;y.stackState.push(y.stackState[G-1]+b)}var b=this.options,c=this.yAxis.waterfall.stacks,d=b.threshold,e=d||0,h=e,k=this.stackKey,
l=this.xData,m=l.length,n,p,r;this.yAxis.stacking.usePercentage=!1;var t=p=r=e;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var u=c.changed;(n=c.alreadyChanged)&&0>n.indexOf(k)&&(u=!0);c[k]||(c[k]={});n=c[k];for(var x=0;x<m;x++){var z=l[x];if(!n[z]||u)n[z]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:u&&n[z]?n[z].label:void 0};var y=n[z];var E=this.yData[x];0<=E?y.posTotal+=E:y.negTotal+=E;var B=b.data[x];z=y.absolutePos=y.posTotal;var D=y.absoluteNeg=
y.negTotal;y.stackTotal=z+D;var G=y.stackState.length;B&&B.isIntermediateSum?(a(r,p,0,r),r=p,p=d,e^=h,h^=e,e^=h):B&&B.isSum?(a(d,t,G),e=d):(a(e,E,0,t),B&&(t+=E,p+=E));y.stateIndex++;y.threshold=e;e+=y.stackTotal}c.changed=!1;c.alreadyChanged||(c.alreadyChanged=[]);c.alreadyChanged.push(k)}};c.prototype.getExtremes=function(){var a=this.options.stacking;if(a){var b=this.yAxis;b=b.waterfall.stacks;var c=this.stackedYNeg=[];var d=this.stackedYPos=[];"overlap"===a?D(b[this.stackKey],function(a){c.push(k(a.stackState));
d.push(n(a.stackState))}):D(b[this.stackKey],function(a){c.push(a.negTotal+a.threshold);d.push(a.posTotal+a.threshold)});return{dataMin:k(c),dataMax:n(d)}}return{dataMin:this.dataMin,dataMax:this.dataMax}};c.defaultOptions=z(x.defaultOptions,{dataLabels:{inside:!0},lineWidth:1,lineColor:h.neutralColor80,dashStyle:"Dot",borderColor:h.neutralColor80,states:{hover:{lineWidthPlus:0}}});return c}(x);r(a.prototype,{getZonesGraphs:b.prototype.getZonesGraphs,pointValKey:"y",showLine:!0,pointClass:m});d.registerSeriesType("waterfall",
a);t.compose(e,c);"";return a});z(e,"Extensions/Polar.js",[e["Core/Animation/AnimationUtilities.js"],e["Core/Chart/Chart.js"],e["Core/Globals.js"],e["Extensions/Pane.js"],e["Core/Pointer.js"],e["Core/Series/Series.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Renderer/SVG/SVGRenderer.js"],e["Core/Utilities.js"]],function(e,c,h,d,a,t,m,l,r){var x=e.animObject;m=m.seriesTypes;var b=r.addEvent,n=r.defined,k=r.find,p=r.isNumber,y=r.pick,z=r.splat,D=r.uniqueKey;e=r.wrap;var H=t.prototype;a=a.prototype;
H.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};H.getConnectors=function(a,b,c,d){var e=d?1:0;var g=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>g-1?a.length-(1+e):g-1;e=g+1>a.length-1?e:g+1;var f=a[b];e=a[e];var h=f.plotX;f=f.plotY;var k=e.plotX;var q=e.plotY;e=a[g].plotX;g=a[g].plotY;h=(1.5*e+h)/2.5;f=(1.5*g+f)/2.5;k=(1.5*e+k)/2.5;var l=(1.5*g+q)/2.5;q=Math.sqrt(Math.pow(h-
e,2)+Math.pow(f-g,2));var m=Math.sqrt(Math.pow(k-e,2)+Math.pow(l-g,2));h=Math.atan2(f-g,h-e);l=Math.PI/2+(h+Math.atan2(l-g,k-e))/2;Math.abs(h-l)>Math.PI/2&&(l-=Math.PI);h=e+Math.cos(l)*q;f=g+Math.sin(l)*q;k=e+Math.cos(Math.PI+l)*m;l=g+Math.sin(Math.PI+l)*m;e={rightContX:k,rightContY:l,leftContX:h,leftContY:f,plotX:e,plotY:g};c&&(e.prevPointCont=this.getConnectors(a,b,!1,d));return e};H.toXY=function(a){var b=this.chart,c=this.xAxis,d=this.yAxis,e=a.plotX,f=a.plotY,h=a.series,k=b.inverted,l=a.y,m=
k?e:d.len-f;k&&h&&!h.isRadialBar&&(a.plotY=f="number"===typeof l?d.translate(l)||0:0);a.rectPlotX=e;a.rectPlotY=f;d.center&&(m+=d.center[3]/2);p(f)&&(d=k?d.postTranslate(f,m):c.postTranslate(e,m),a.plotX=a.polarPlotX=d.x-b.plotLeft,a.plotY=a.polarPlotY=d.y-b.plotTop);this.kdByAngle?(b=(e/Math.PI*180+c.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX};m.spline&&(e(m.spline.prototype,"getPointSpline",function(a,b,c,d){this.chart.polar?d?(a=this.getConnectors(b,d,!0,this.connectEnds),
b=a.prevPointCont&&a.prevPointCont.rightContX,c=a.prevPointCont&&a.prevPointCont.rightContY,a=["C",p(b)?b:a.plotX,p(c)?c:a.plotY,p(a.leftContX)?a.leftContX:a.plotX,p(a.leftContY)?a.leftContY:a.plotY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,d);return a}),m.areasplinerange&&(m.areasplinerange.prototype.getPointSpline=m.spline.prototype.getPointSpline));b(t,"afterTranslate",function(){var a=this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=a.tooltip&&a.tooltip.shared)?this.searchPoint=
this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var c=this.points,d=c.length;d--;)this.toXY(c[d]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&c[d].y<this.yAxis.min&&(c[d].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!this.eventsToUnbind.push(b(this,"afterRender",function(){if(a.polar){var b=this.yAxis.pane.center;this.clipCircle?this.clipCircle.animate({x:b[0],y:b[1],r:b[2]/2,innerR:b[3]/2}):this.clipCircle=a.renderer.clipCircle(b[0],
b[1],b[2]/2,b[3]/2);this.group.clip(this.clipCircle);this.setClip=h.noop}})))}},{order:2});e(m.line.prototype,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof e){this.connectEnds=!0;b.splice(b.length,0,b[e]);var g=!0}b.forEach(function(a){"undefined"===typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));g&&b.pop();return d});var u=function(a,
b){var c=this,d=this.chart,e=this.options.animation,g=this.group,f=this.markerGroup,k=this.xAxis.center,l=d.plotLeft,m=d.plotTop,n,p,r,t;if(d.polar)if(c.isRadialBar)b||(c.startAngleRad=y(c.translatedThreshold,c.xAxis.startAngleRad),h.seriesTypes.pie.prototype.animate.call(c,b));else{if(d.renderer.isSVG)if(e=x(e),c.is("column")){if(!b){var u=k[3]/2;c.points.forEach(function(a){n=a.graphic;r=(p=a.shapeArgs)&&p.r;t=p&&p.innerR;n&&p&&(n.attr({r:u,innerR:u}),n.animate({r:r,innerR:t},c.options.animation))})}}else b?
(a={translateX:k[0]+l,translateY:k[1]+m,scaleX:.001,scaleY:.001},g.attr(a),f&&f.attr(a)):(a={translateX:l,translateY:m,scaleX:1,scaleY:1},g.animate(a,e),f&&f.animate(a,e))}else a.call(this,b)};e(H,"animate",u);if(m.column){var I=m.arearange.prototype;m=m.column.prototype;m.polarArc=function(a,b,c,d){var e=this.xAxis.center,g=this.yAxis.len,f=e[3]/2;b=g-b+f;a=g-y(a,g)+f;this.yAxis.reversed&&(0>b&&(b=f),0>a&&(a=f));return{x:e[0],y:e[1],r:b,innerR:a,start:c,end:d}};e(m,"animate",u);e(m,"translate",function(a){var b=
this.options,c=b.stacking,d=this.chart,e=this.xAxis,f=this.yAxis,h=f.reversed,k=f.center,l=e.startAngleRad,m=e.endAngleRad-l;this.preventPostTranslate=!0;a.call(this);if(e.isRadial){a=this.points;e=a.length;var t=f.translate(f.min);var u=f.translate(f.max);b=b.threshold||0;if(d.inverted&&p(b)){var x=f.translate(b);n(x)&&(0>x?x=0:x>m&&(x=m),this.translatedThreshold=x+l)}for(;e--;){b=a[e];var y=b.barX;var z=b.x;var B=b.y;b.shapeType="arc";if(d.inverted){b.plotY=f.translate(B);if(c&&f.stacking){if(B=
f.stacking.stacks[(0>B?"-":"")+this.stackKey],this.visible&&B&&B[z]&&!b.isNull){var D=B[z].points[this.getStackIndicator(void 0,z,this.index).key];var E=f.translate(D[0]);D=f.translate(D[1]);n(E)&&(E=r.clamp(E,0,m))}}else E=x,D=b.plotY;E>D&&(D=[E,E=D][0]);if(!h)if(E<t)E=t;else if(D>u)D=u;else{if(D<t||E>u)E=D=0}else if(D>t)D=t;else if(E<u)E=u;else if(E>t||D<u)E=D=m;f.min>f.max&&(E=D=h?m:0);E+=l;D+=l;k&&(b.barX=y+=k[3]/2);z=Math.max(y,0);B=Math.max(y+b.pointWidth,0);b.shapeArgs={x:k&&k[0],y:k&&k[1],
r:B,innerR:z,start:E,end:D};b.opacity=E===D?0:void 0;b.plotY=(n(this.translatedThreshold)&&(E<this.translatedThreshold?E:D))-l}else E=y+l,b.shapeArgs=this.polarArc(b.yBottom,b.plotY,E,E+b.pointWidth);this.toXY(b);d.inverted?(y=f.postTranslate(b.rectPlotY,y+b.pointWidth/2),b.tooltipPos=[y.x-d.plotLeft,y.y-d.plotTop]):b.tooltipPos=[b.plotX,b.plotY];k&&(b.ttBelow=b.plotY>k[1])}}});m.findAlignments=function(a,b){null===b.align&&(b.align=20<a&&160>a?"left":200<a&&340>a?"right":"center");null===b.verticalAlign&&
(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b};I&&(I.findAlignments=m.findAlignments);e(m,"alignDataLabel",function(a,b,c,d,e,h){var f=this.chart,g=y(d.inside,!!this.options.stacking);f.polar?(a=b.rectPlotX/Math.PI*180,f.inverted?(this.forceDL=f.isInsidePlot(b.plotX,Math.round(b.plotY)),g&&b.shapeArgs?(e=b.shapeArgs,e=this.yAxis.postTranslate(((e.start||0)+(e.end||0))/2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),e={x:e.x-f.plotLeft,y:e.y-f.plotTop}):b.tooltipPos&&
(e={x:b.tooltipPos[0],y:b.tooltipPos[1]}),d.align=y(d.align,"center"),d.verticalAlign=y(d.verticalAlign,"middle")):this.findAlignments&&(d=this.findAlignments(a,d)),H.alignDataLabel.call(this,b,c,d,e,h),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end&&c.hide(!0)):a.call(this,b,c,d,e,h)})}e(a,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=a.isXAxis,f=a.center;if("colorAxis"!==a.coll){var g=b.chartX-f[0]-c.plotLeft;f=
b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d});l.prototype.clipCircle=function(a,b,c,d){var e=D(),f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=d?this.arc(a,b,c,d,0,2*Math.PI).add(f):this.circle(a,b,c).add(f);a.id=e;a.clipPath=f;return a};b(c,"getAxes",function(){this.pane||(this.pane=[]);this.options.pane=z(this.options.pane);this.options.pane.forEach(function(a){new d(a,
this)},this)});b(c,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});b(t,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});e(c.prototype,"get",function(a,b){return k(this.pane||[],function(a){return a.options.id===b})||a.call(this,b)})});z(e,"masters/highcharts-more.src.js",[e["Core/Globals.js"],e["Core/Axis/RadialAxis.js"],e["Series/Bubble/BubbleSeries.js"]],function(e,c,h){c.compose(e.Axis,e.Tick);
h.compose(e.Chart,e.Legend,e.Series)})});
//# sourceMappingURL=highcharts-more.js.map